% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
  ignorenonframetext,
]{beamer}
\usepackage{pgfpages}
\setbeamertemplate{caption}[numbered]
\setbeamertemplate{caption label separator}{: }
\setbeamercolor{caption name}{fg=normal text.fg}
\beamertemplatenavigationsymbolsempty
% Prevent slide breaks in the middle of a paragraph
\widowpenalties 1 10000
\raggedbottom
\setbeamertemplate{part page}{
  \centering
  \begin{beamercolorbox}[sep=16pt,center]{part title}
    \usebeamerfont{part title}\insertpart\par
  \end{beamercolorbox}
}
\setbeamertemplate{section page}{
  \centering
  \begin{beamercolorbox}[sep=12pt,center]{section title}
    \usebeamerfont{section title}\insertsection\par
  \end{beamercolorbox}
}
\setbeamertemplate{subsection page}{
  \centering
  \begin{beamercolorbox}[sep=8pt,center]{subsection title}
    \usebeamerfont{subsection title}\insertsubsection\par
  \end{beamercolorbox}
}
\AtBeginPart{
  \frame{\partpage}
}
\AtBeginSection{
  \ifbibliography
  \else
    \frame{\sectionpage}
  \fi
}
\AtBeginSubsection{
  \frame{\subsectionpage}
}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\usetheme[]{Montpellier}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\newif\ifbibliography
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
\usepackage{caption}
% Make caption package work with longtable
\makeatletter
\def\fnum@table{\tablename~\thetable}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
%\documentclass[unicode,10pt]{beamer}% 'unicode'が必要
\usepackage{luatexja}% 日本語を使う場合は必須
%\usepackage[japanese]{babel}	
%\usefonttheme[onlymath]{serif}
%\usepackage[T1]{fontenc} %これを使うと、ギリシャ文字が出ない
%\usepackage{textcomp}
%\usepackage[scale=1.0]{tgheros} % Sans serif font
%\usepackage[scaled]{beramono} % Monospace font
%\usepackage{luatexja-otf}
%\renewcommand{\kanjifamilydefault}{\gtdefault}
%\usepackage[haranoaji]{luatexja-preset}

% スライド番号の表示 %%%%%%%%%%%%%%%%%%%
\makeatletter
\setbeamertemplate{footline}{%
  \leavevmode%
  \hbox{%
  \begin{beamercolorbox}[wd=.5\paperwidth,ht=2.25ex,dp=1ex,right]{date in head/foot}%
    \insertframenumber{} \hspace*{2ex} % new version without total frames
  \end{beamercolorbox}}%
  \vskip0pt%
}
\makeatother
% スライド番号の表示 %%%%%%%%%%%%%%%%%%%
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{第14章: 発展的なパネルデータ法}
\subtitle{Jeffrey Wooldridge (2016).\\
Introductory Econometrics: A Modern Approach\\
Seventh Edition. Cengage Learning.}
\author{}
\date{\vspace{-2.5em}2026-03-06}

\begin{document}
\frame{\titlepage}

\section{準備}\label{ux6e96ux5099}

\begin{frame}[fragile]{必要なパッケージの読み込み}
\phantomsection\label{ux5fc5ux8981ux306aux30d1ux30c3ux30b1ux30fcux30b8ux306eux8aadux307fux8fbcux307f}
\begin{itemize}
\tightlist
\item
  \texttt{wooldridge}パッケージの読み込み
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(wooldridge)}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  \texttt{plm}パッケージの読み込み（パネルデータ分析に使用）
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(plm)}
\end{Highlighting}
\end{Shaded}
\end{frame}

\section{14-1 固定効果推定}\label{ux56faux5b9aux52b9ux679cux63a8ux5b9a}

\begin{frame}{固定効果変換 (Fixed Effects Transformation)}
\phantomsection\label{ux56faux5b9aux52b9ux679cux5909ux63db-fixed-effects-transformation}
\begin{itemize}
\tightlist
\item
  モデル:
  \(y_{it} = \beta_1 x_{it} + a_i + u_{it}, \quad t = 1, 2, \dots, T\)
  \hfill {[}14.1{]}
\item
  個体 \(i\) に関して時間平均をとると：
  \[\bar{y}_i = \beta_1 \bar{x}_i + a_i + \bar{u}_i \hfill [14.2]\]
\item
  {[}14.1{]} から {[}14.2{]} を引く（\textbf{固定効果変換} /
  within変換）：
  \[\ddot{y}_{it} = \beta_1 \ddot{x}_{it} + \ddot{u}_{it}, \quad t = 1, 2, \dots, T \hfill [14.3]\]
\item
  \(\ddot{y}_{it} = y_{it} - \bar{y}_i\)：\textbf{時間平均除去データ}
  (time-demeaned data)
\item
  \(a_i\) が消去される \(\Rightarrow\) OLSで \(\beta_1\)
  を一致推定できる
\end{itemize}
\end{frame}

\begin{frame}{固定効果推定量の特性}
\phantomsection\label{ux56faux5b9aux52b9ux679cux63a8ux5b9aux91cfux306eux7279ux6027}
\begin{itemize}
\tightlist
\item
  {[}14.3{]} を Pooled OLS で推定したものが
  \textbf{固定効果推定量}（\textbf{within推定量}）
\item
  \textbf{時間不変の変数}（出生地、性別など）は時間平均除去によって消去され、推定不可能
\item
  厳密外生性仮定（\(\text{E}(u_{it}|\mathbf{X}_i, a_i) = 0\)）のもとで不偏・一致
\item
  \(a_i\) と \(x_{it}\)
  が任意に相関していても構わない（第13章のFDと同じ強み）
\item
  自由度:
  \(df = NT - N - k = N(T-1) - k\)（時間平均除去により個体ごとに自由度を1失う）
\end{itemize}
\end{frame}

\begin{frame}{複数の説明変数への拡張}
\phantomsection\label{ux8907ux6570ux306eux8aacux660eux5909ux6570ux3078ux306eux62e1ux5f35}
\begin{itemize}
\tightlist
\item
  一般的な観測不能効果モデル {[}14.4{]}:
  \[y_{it} = \beta_1 x_{it1} + \beta_2 x_{it2} + \cdots + \beta_k x_{itk} + a_i + u_{it}\]
\item
  各変数を時間平均除去 \(\Rightarrow\) {[}14.5{]}:
  \[\ddot{y}_{it} = \beta_1 \ddot{x}_{it1} + \beta_2 \ddot{x}_{it2} + \cdots + \beta_k \ddot{x}_{itk} + \ddot{u}_{it}\]
\item
  これをPooled OLSで推定する
\end{itemize}
\end{frame}

\begin{frame}[fragile]{例14.1: 職業訓練が不良品率に与える影響 (JTRAIN)}
\phantomsection\label{ux4f8b14.1-ux8077ux696dux8a13ux7df4ux304cux4e0dux826fux54c1ux7387ux306bux4e0eux3048ux308bux5f71ux97ff-jtrain}
\begin{itemize}
\tightlist
\item
  データ: 54社 × 3年（1987〜1989年）
\item
  従属変数: \(\log(scrap_{it})\)（不良品率の対数）
\item
  説明変数: 年ダミー \(d88\), \(d89\), 補助金 \(grant\), ラグ補助金
  \(grant_{-1}\)
\item
  \(df = 54(3-1) - 4 = 104\)
\end{itemize}

\footnotesize

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(jtrain)}
\NormalTok{pdata\_jt }\OtherTok{\textless{}{-}} \FunctionTok{pdata.frame}\NormalTok{(jtrain, }\AttributeTok{index =} \FunctionTok{c}\NormalTok{(}\StringTok{"fcode"}\NormalTok{, }\StringTok{"year"}\NormalTok{))}
\NormalTok{res\_fe141 }\OtherTok{\textless{}{-}} \FunctionTok{plm}\NormalTok{(lscrap }\SpecialCharTok{\textasciitilde{}}\NormalTok{ d88 }\SpecialCharTok{+}\NormalTok{ d89 }\SpecialCharTok{+}\NormalTok{ grant }\SpecialCharTok{+}\NormalTok{ grant\_1,}
                 \AttributeTok{data =}\NormalTok{ pdata\_jt, }\AttributeTok{model =} \StringTok{"within"}\NormalTok{,}
                 \AttributeTok{na.action =}\NormalTok{ na.omit)}
\FunctionTok{summary}\NormalTok{(res\_fe141)}\SpecialCharTok{$}\NormalTok{coefficients}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##            Estimate Std. Error    t-value   Pr(>|t|)
## d88     -0.08021567  0.1094751 -0.7327297 0.46537158
## d89     -0.24720279  0.1332183 -1.8556220 0.06633916
## grant   -0.25231487  0.1506290 -1.6750751 0.09692392
## grant_1 -0.42158951  0.2102000 -2.0056593 0.04748974
\end{verbatim}

\normalsize
\end{frame}

\begin{frame}{例14.1: 結果の解釈}
\phantomsection\label{ux4f8b14.1-ux7d50ux679cux306eux89e3ux91c8}
\begin{itemize}
\tightlist
\item
  \(\hat{\beta}_{grant_{-1}} \approx -0.422\)：前年に補助金を受けると不良品率が約34\%低下
  {[}\(\exp(-0.422) - 1 \approx -0.344\){]}、5\%水準で有意
\item
  \(\hat{\beta}_{grant} \approx -0.252\)：当年補助金は10\%水準で有意（即時効果は小さい）
\item
  \(d89\) の係数が負 \(\Rightarrow\)
  補助金とは無関係に1989年の生産性は上昇 \(\Rightarrow\)
  年ダミーを含めることの重要性
\end{itemize}
\end{frame}

\begin{frame}[fragile]{例14.2: 教育収益率の時間変化 (WAGEPAN)}
\phantomsection\label{ux4f8b14.2-ux6559ux80b2ux53ceux76caux7387ux306eux6642ux9593ux5909ux5316-wagepan}
\begin{itemize}
\tightlist
\item
  データ: 545人 × 8年（1980〜1987年）、WAGEPAN
\item
  固定効果では \texttt{educ}（時間不変）は推定不可 \(\Rightarrow\)
  \texttt{educ\ ×\ 年ダミー} の交差項を使用
\end{itemize}

\footnotesize

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(wagepan)}
\NormalTok{pdata\_wp }\OtherTok{\textless{}{-}} \FunctionTok{pdata.frame}\NormalTok{(wagepan, }\AttributeTok{index =} \FunctionTok{c}\NormalTok{(}\StringTok{"nr"}\NormalTok{, }\StringTok{"year"}\NormalTok{))}
\NormalTok{res\_fe142 }\OtherTok{\textless{}{-}} \FunctionTok{plm}\NormalTok{(lwage }\SpecialCharTok{\textasciitilde{}}\NormalTok{ married }\SpecialCharTok{+}\NormalTok{ union }\SpecialCharTok{+}\NormalTok{ exper }\SpecialCharTok{+}\NormalTok{ expersq }\SpecialCharTok{+}
\NormalTok{                   d81 }\SpecialCharTok{+}\NormalTok{ d82 }\SpecialCharTok{+}\NormalTok{ d83 }\SpecialCharTok{+}\NormalTok{ d84 }\SpecialCharTok{+}\NormalTok{ d85 }\SpecialCharTok{+}\NormalTok{ d86 }\SpecialCharTok{+}\NormalTok{ d87 }\SpecialCharTok{+}
                   \FunctionTok{I}\NormalTok{(educ }\SpecialCharTok{*}\NormalTok{ d81) }\SpecialCharTok{+} \FunctionTok{I}\NormalTok{(educ }\SpecialCharTok{*}\NormalTok{ d82) }\SpecialCharTok{+} \FunctionTok{I}\NormalTok{(educ }\SpecialCharTok{*}\NormalTok{ d83) }\SpecialCharTok{+}
                   \FunctionTok{I}\NormalTok{(educ }\SpecialCharTok{*}\NormalTok{ d84) }\SpecialCharTok{+} \FunctionTok{I}\NormalTok{(educ }\SpecialCharTok{*}\NormalTok{ d85) }\SpecialCharTok{+} \FunctionTok{I}\NormalTok{(educ }\SpecialCharTok{*}\NormalTok{ d86) }\SpecialCharTok{+}
                   \FunctionTok{I}\NormalTok{(educ }\SpecialCharTok{*}\NormalTok{ d87),}
                 \AttributeTok{data =}\NormalTok{ pdata\_wp, }\AttributeTok{model =} \StringTok{"within"}\NormalTok{)}
\CommentTok{\# 交差項の係数のみ表示}
\FunctionTok{coef}\NormalTok{(res\_fe142)[}\FunctionTok{grep}\NormalTok{(}\StringTok{"educ"}\NormalTok{, }\FunctionTok{names}\NormalTok{(}\FunctionTok{coef}\NormalTok{(res\_fe142)))]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## I(educ * d81) I(educ * d82) I(educ * d83) I(educ * d84) I(educ * d85) 
##   0.004990619   0.001650951  -0.002662147  -0.009825689  -0.009214474 
## I(educ * d86) I(educ * d87) 
##  -0.012138164  -0.015789160
\end{verbatim}

\normalsize
\end{frame}

\begin{frame}{例14.2: 解釈}
\phantomsection\label{ux4f8b14.2-ux89e3ux91c8}
\begin{itemize}
\tightlist
\item
  \(d87 \cdot educ\) の係数
  \(\approx 0.030\)（\(t \approx 2.48\)）：最大
\item
  1987年の教育収益率は基準年（1980年）より約3\%ポイント高い
\item
  交差項7本の結合有意性検定: \(p値 \approx 0.28\)（まとめて有意でない）
\item
  教育収益率は1980〜1987年を通じてほぼ一定という結論
\end{itemize}
\end{frame}

\section{14-1a
ダミー変数回帰}\label{a-ux30c0ux30dfux30fcux5909ux6570ux56deux5e30}

\begin{frame}{ダミー変数回帰 (Dummy Variable Regression)}
\phantomsection\label{ux30c0ux30dfux30fcux5909ux6570ux56deux5e30-dummy-variable-regression}
\begin{itemize}
\tightlist
\item
  \(a_i\) を各個体のパラメータとして推定する伝統的な方法
\item
  \(N\) 個の切片ダミー変数を説明変数に含めてOLS推定 \(\Rightarrow\)
  \textbf{ダミー変数回帰}
\item
  \textbf{重要な性質}: ダミー変数回帰は固定効果推定量と\textbf{全く同じ}
  \(\hat{\beta}_j\) を与える
\item
  固定効果推定後、各個体の固定効果の推定値 {[}14.6{]}:
  \[\hat{a}_i = \bar{y}_i - \hat{\beta}_1 \bar{x}_{i1} - \cdots - \hat{\beta}_k \bar{x}_{ik}\]
\item
  \(N\) が大きい場合、ダミー変数回帰は非実用的（変数が多すぎる）
\end{itemize}
\end{frame}

\section{14-1b 固定効果 vs
1階差分}\label{b-ux56faux5b9aux52b9ux679c-vs-1ux968eux5deeux5206}

\begin{frame}{固定効果法 (FE) と 1階差分法 (FD) の比較}
\phantomsection\label{ux56faux5b9aux52b9ux679cux6cd5-fe-ux3068-1ux968eux5deeux5206ux6cd5-fd-ux306eux6bd4ux8f03}
\begin{longtable}[]{@{}lll@{}}
\toprule\noalign{}
特徴 & FE (固定効果) & FD (1階差分) \\
\midrule\noalign{}
\endhead
\(T=2\) のとき & \textbf{同一} & \textbf{同一} \\
\(T \geq 3\) のとき & 異なる推定量 & 異なる推定量 \\
\(u_{it}\) が系列無相関 & \textbf{効率的} & 非効率 \\
\(u_{it}\) がランダムウォーク & 非効率 & \textbf{効率的} \\
測定誤差に対する感度 & 高い & 高い \\
\bottomrule\noalign{}
\end{longtable}

\begin{itemize}
\tightlist
\item
  \(T = 2\): FEとFDは同一 \(\Rightarrow\) どちらでも良い
\item
  \(T \geq 3\): \(u_{it}\) の系列相関構造で選択

  \begin{itemize}
  \tightlist
  \item
    系列無相関 \(\Rightarrow\) FEが優れる
  \item
    ランダムウォーク的正の系列相関 \(\Rightarrow\) FDが優れる
  \end{itemize}
\end{itemize}
\end{frame}

\section{14-1c
不均衡パネル}\label{c-ux4e0dux5747ux8861ux30d1ux30cdux30eb}

\begin{frame}{不均衡パネルの固定効果推定}
\phantomsection\label{ux4e0dux5747ux8861ux30d1ux30cdux30ebux306eux56faux5b9aux52b9ux679cux63a8ux5b9a}
\begin{itemize}
\tightlist
\item
  \textbf{不均衡パネル (unbalanced panel)}: 一部の個体で欠損期間がある
\item
  個体 \(i\) の観測期間数を \(T_i\) とすると、総観測数
  \(= T_1 + T_2 + \cdots + T_N\)
\item
  時間平均除去は個体ごとに \(T_i\) 期間の平均を使う
\item
  固定効果推定は不均衡パネルでも同様に適用可能
\item
  注意:
  欠損が\textbf{自己選択的}（離脱が誤差項と相関）な場合はバイアスが生じる

  \begin{itemize}
  \tightlist
  \item
    ただしFEは \(a_i\)
    と選択指標の相関を許容するため、FDより頑健な場合がある
  \end{itemize}
\end{itemize}
\end{frame}

\begin{frame}[fragile]{例14.3: 不均衡パネルでの職業訓練効果 (JTRAIN)}
\phantomsection\label{ux4f8b14.3-ux4e0dux5747ux8861ux30d1ux30cdux30ebux3067ux306eux8077ux696dux8a13ux7df4ux52b9ux679c-jtrain}
\begin{itemize}
\tightlist
\item
  \texttt{sales}（売上の対数）と \texttt{employ}（従業員数の対数）を追加
\item
  3社が完全に脱落、5観測が追加欠損 \(\Rightarrow\) \(n = 148\)
\end{itemize}

\footnotesize

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{res\_fe143 }\OtherTok{\textless{}{-}} \FunctionTok{plm}\NormalTok{(lscrap }\SpecialCharTok{\textasciitilde{}}\NormalTok{ d88 }\SpecialCharTok{+}\NormalTok{ d89 }\SpecialCharTok{+}\NormalTok{ grant }\SpecialCharTok{+}\NormalTok{ grant\_1 }\SpecialCharTok{+}
\NormalTok{                   lsales }\SpecialCharTok{+}\NormalTok{ lemploy,}
                 \AttributeTok{data =}\NormalTok{ pdata\_jt, }\AttributeTok{model =} \StringTok{"within"}\NormalTok{,}
                 \AttributeTok{na.action =}\NormalTok{ na.omit)}
\FunctionTok{summary}\NormalTok{(res\_fe143)}\SpecialCharTok{$}\NormalTok{coefficients[}\FunctionTok{c}\NormalTok{(}\StringTok{"grant"}\NormalTok{, }\StringTok{"grant\_1"}\NormalTok{), ]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           Estimate Std. Error   t-value   Pr(>|t|)
## grant   -0.2967542  0.1570861 -1.889119 0.06206040
## grant_1 -0.5355783  0.2242060 -2.388778 0.01896951
\end{verbatim}

\normalsize

\begin{itemize}
\tightlist
\item
  \(\hat{\beta}_{grant} \approx -0.297\)、\(\hat{\beta}_{grant_{-1}} \approx -0.536\)：基本結果と整合的
\end{itemize}
\end{frame}

\section{14-2
変量効果モデル}\label{ux5909ux91cfux52b9ux679cux30e2ux30c7ux30eb}

\begin{frame}{変量効果モデルの設定}
\phantomsection\label{ux5909ux91cfux52b9ux679cux30e2ux30c7ux30ebux306eux8a2dux5b9a}
\begin{itemize}
\tightlist
\item
  同じ不観測効果モデルから出発 {[}14.7{]}:
  \[y_{it} = \beta_0 + \beta_1 x_{it1} + \cdots + \beta_k x_{itk} + a_i + u_{it}\]
\item
  \textbf{変量効果 (RE) の仮定} {[}14.8{]}:
  \[\text{Cov}(x_{itj}, a_i) = 0, \quad t = 1, \dots, T;\ j = 1, \dots, k\]
\item
  \(a_i\) がすべての説明変数と無相関と仮定 \(\Rightarrow\) \(a_i\)
  を誤差項に含める
\item
  \textbf{合成誤差項}: \(v_{it} = a_i + u_{it}\)
\item
  \(a_i\) が各期間の誤差に入るため、\(v_{it}\)
  は時間を通じて正の系列相関を持つ
\end{itemize}
\end{frame}

\begin{frame}{GLS変換（準時間平均除去）}
\phantomsection\label{glsux5909ux63dbux6e96ux6642ux9593ux5e73ux5747ux9664ux53bb}
\begin{itemize}
\tightlist
\item
  合成誤差の系列相関を除去するため一般化最小二乗法 (GLS) を適用
\item
  変換パラメータ {[}14.10{]}:
  \[\theta = 1 - \left[\sigma_u^2 / (\sigma_u^2 + T\sigma_a^2)\right]^{1/2}\]
\item
  変換後の方程式 {[}14.11{]}:
  \[y_{it} - \theta\bar{y}_i = \beta_0(1-\theta) + \beta_1(x_{it1} - \theta\bar{x}_{i1}) + \cdots + (v_{it} - \theta\bar{v}_i)\]
\item
  \textbf{quasi-demeaned（準時間平均除去）データ}に基づくPooled OLS
  \(\Rightarrow\) \textbf{変量効果推定量}
\item
  \(\theta = 0\): Pooled OLS と同一
\item
  \(\theta = 1\): 固定効果推定量と同一
\end{itemize}
\end{frame}

\begin{frame}[fragile]{例14.4: 賃金方程式 (WAGEPAN)}
\phantomsection\label{ux4f8b14.4-ux8cc3ux91d1ux65b9ux7a0bux5f0f-wagepan}
\begin{itemize}
\tightlist
\item
  3手法（Pooled OLS, RE, FE）の比較
\end{itemize}

\footnotesize

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Pooled OLS（参考）}
\NormalTok{res\_pols }\OtherTok{\textless{}{-}} \FunctionTok{plm}\NormalTok{(lwage }\SpecialCharTok{\textasciitilde{}}\NormalTok{ educ }\SpecialCharTok{+}\NormalTok{ black }\SpecialCharTok{+}\NormalTok{ hisp }\SpecialCharTok{+}\NormalTok{ exper }\SpecialCharTok{+}\NormalTok{ expersq }\SpecialCharTok{+}
\NormalTok{                  married }\SpecialCharTok{+}\NormalTok{ union }\SpecialCharTok{+}
\NormalTok{                  d81 }\SpecialCharTok{+}\NormalTok{ d82 }\SpecialCharTok{+}\NormalTok{ d83 }\SpecialCharTok{+}\NormalTok{ d84 }\SpecialCharTok{+}\NormalTok{ d85 }\SpecialCharTok{+}\NormalTok{ d86 }\SpecialCharTok{+}\NormalTok{ d87,}
                \AttributeTok{data =}\NormalTok{ pdata\_wp, }\AttributeTok{model =} \StringTok{"pooling"}\NormalTok{)}
\CommentTok{\# 変量効果 (RE)}
\NormalTok{res\_re }\OtherTok{\textless{}{-}} \FunctionTok{plm}\NormalTok{(lwage }\SpecialCharTok{\textasciitilde{}}\NormalTok{ educ }\SpecialCharTok{+}\NormalTok{ black }\SpecialCharTok{+}\NormalTok{ hisp }\SpecialCharTok{+}\NormalTok{ exper }\SpecialCharTok{+}\NormalTok{ expersq }\SpecialCharTok{+}
\NormalTok{                married }\SpecialCharTok{+}\NormalTok{ union }\SpecialCharTok{+}
\NormalTok{                d81 }\SpecialCharTok{+}\NormalTok{ d82 }\SpecialCharTok{+}\NormalTok{ d83 }\SpecialCharTok{+}\NormalTok{ d84 }\SpecialCharTok{+}\NormalTok{ d85 }\SpecialCharTok{+}\NormalTok{ d86 }\SpecialCharTok{+}\NormalTok{ d87,}
              \AttributeTok{data =}\NormalTok{ pdata\_wp, }\AttributeTok{model =} \StringTok{"random"}\NormalTok{)}
\CommentTok{\# 固定効果 (FE)}
\NormalTok{res\_fe }\OtherTok{\textless{}{-}} \FunctionTok{plm}\NormalTok{(lwage }\SpecialCharTok{\textasciitilde{}}\NormalTok{ expersq }\SpecialCharTok{+}\NormalTok{ married }\SpecialCharTok{+}\NormalTok{ union }\SpecialCharTok{+}
\NormalTok{                d81 }\SpecialCharTok{+}\NormalTok{ d82 }\SpecialCharTok{+}\NormalTok{ d83 }\SpecialCharTok{+}\NormalTok{ d84 }\SpecialCharTok{+}\NormalTok{ d85 }\SpecialCharTok{+}\NormalTok{ d86 }\SpecialCharTok{+}\NormalTok{ d87,}
              \AttributeTok{data =}\NormalTok{ pdata\_wp, }\AttributeTok{model =} \StringTok{"within"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\normalsize
\end{frame}

\begin{frame}[fragile]{例14.4: 結果の比較}
\phantomsection\label{ux4f8b14.4-ux7d50ux679cux306eux6bd4ux8f03}
\footnotesize

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 時間変動変数の係数比較}
\NormalTok{vars }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"expersq"}\NormalTok{, }\StringTok{"married"}\NormalTok{, }\StringTok{"union"}\NormalTok{)}
\FunctionTok{rbind}\NormalTok{(}
  \AttributeTok{POLS =} \FunctionTok{coef}\NormalTok{(res\_pols)[vars],}
  \AttributeTok{RE   =} \FunctionTok{coef}\NormalTok{(res\_re)[vars],}
  \AttributeTok{FE   =} \FunctionTok{coef}\NormalTok{(res\_fe)[vars]}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           expersq    married      union
## POLS -0.002411703 0.10825295 0.18246128
## RE   -0.004723943 0.06398602 0.10613443
## FE   -0.005185498 0.04668036 0.08000186
\end{verbatim}

\normalsize
\end{frame}

\begin{frame}[fragile]{例14.4: 解釈}
\phantomsection\label{ux4f8b14.4-ux89e3ux91c8}
\begin{itemize}
\tightlist
\item
  \(\hat{\theta} \approx 0.643\)：REはPooled OLSとFEの中間
\item
  \texttt{married} の係数: POLS(0.108) \(>\) RE(0.064) \(>\) FE(0.047)

  \begin{itemize}
  \tightlist
  \item
    能力の高い人が結婚しやすい \(\Rightarrow\) POLS/REは上方バイアス
  \end{itemize}
\item
  \texttt{union} の係数: POLS(0.182) \(>\) RE(0.106) \(>\) FE(0.080)

  \begin{itemize}
  \tightlist
  \item
    組合効果の一部は個人固有特性に起因
  \end{itemize}
\item
  FEでは \texttt{educ}, \texttt{black}, \texttt{hispan}
  は時間不変のため推定不可
\end{itemize}
\end{frame}

\section{14-2a 変量効果 vs Pooled
OLS}\label{a-ux5909ux91cfux52b9ux679c-vs-pooled-ols}

\begin{frame}{変量効果とPooled OLSの選択}
\phantomsection\label{ux5909ux91cfux52b9ux679cux3068pooled-olsux306eux9078ux629e}
\begin{itemize}
\tightlist
\item
  Breusch-Pagan (1980) 検定:
  \(H_0: \sigma_a^2 = 0\)（個体効果が存在しない）
\item
  \(\sigma_a^2 = 0\) なら観測不能効果なし \(\Rightarrow\) Pooled
  OLSが適切
\item
  ただし、この検定はあくまで \(\sigma_a^2 > 0\) を確認するもの

  \begin{itemize}
  \tightlist
  \item
    \(\sigma_a^2 > 0\) でも \(a_i\) が \(x_{it}\) と相関していれば
    RE/POLS ともに不一致
  \end{itemize}
\item
  \textbf{実務上の含意}: REはPooled
  OLSより好まれることが多い（特に誤差構造がRE仮定に近い場合）

  \begin{itemize}
  \tightlist
  \item
    系列相関の除去により効率的
  \item
    \(a_i\) の一部を誤差項から除去 \(\Rightarrow\) バイアスを軽減
  \end{itemize}
\end{itemize}
\end{frame}

\section{14-2b 変量効果 vs
固定効果}\label{b-ux5909ux91cfux52b9ux679c-vs-ux56faux5b9aux52b9ux679c}

\begin{frame}[fragile]{FE vs RE の選択基準}
\phantomsection\label{fe-vs-re-ux306eux9078ux629eux57faux6e96}
\begin{itemize}
\tightlist
\item
  \textbf{FE}: \(a_i\) と \(x_{it}\) が相関していてもよい
  \(\Rightarrow\) より頑健
\item
  \textbf{RE}: \(a_i\) と \(x_{it}\) が無相関という仮定が必要
  \(\Rightarrow\) 効率的（標準誤差が小さい）
\item
  \textbf{RE を選ぶ場合}: 主要な説明変数が時間不変（例:
  \texttt{educ}）\(\Rightarrow\) FEでは推定不可
\item
  \textbf{Hausman (1978) 検定}: RE仮定 {[}14.8{]} が成立しているか検定
\end{itemize}

\[H_0: \text{Cov}(x_{itj}, a_i) = 0 \quad \forall j\]
\end{frame}

\begin{frame}[fragile]{Hausman検定の実施}
\phantomsection\label{hausmanux691cux5b9aux306eux5b9fux65bd}
\footnotesize

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Hausman検定（同じ変数セットでFEとREを推定）}
\NormalTok{res\_re\_h }\OtherTok{\textless{}{-}} \FunctionTok{plm}\NormalTok{(lwage }\SpecialCharTok{\textasciitilde{}}\NormalTok{ expersq }\SpecialCharTok{+}\NormalTok{ married }\SpecialCharTok{+}\NormalTok{ union }\SpecialCharTok{+}
\NormalTok{                  d81 }\SpecialCharTok{+}\NormalTok{ d82 }\SpecialCharTok{+}\NormalTok{ d83 }\SpecialCharTok{+}\NormalTok{ d84 }\SpecialCharTok{+}\NormalTok{ d85 }\SpecialCharTok{+}\NormalTok{ d86 }\SpecialCharTok{+}\NormalTok{ d87,}
                \AttributeTok{data =}\NormalTok{ pdata\_wp, }\AttributeTok{model =} \StringTok{"random"}\NormalTok{)}
\NormalTok{res\_fe\_h }\OtherTok{\textless{}{-}} \FunctionTok{plm}\NormalTok{(lwage }\SpecialCharTok{\textasciitilde{}}\NormalTok{ expersq }\SpecialCharTok{+}\NormalTok{ married }\SpecialCharTok{+}\NormalTok{ union }\SpecialCharTok{+}
\NormalTok{                  d81 }\SpecialCharTok{+}\NormalTok{ d82 }\SpecialCharTok{+}\NormalTok{ d83 }\SpecialCharTok{+}\NormalTok{ d84 }\SpecialCharTok{+}\NormalTok{ d85 }\SpecialCharTok{+}\NormalTok{ d86 }\SpecialCharTok{+}\NormalTok{ d87,}
                \AttributeTok{data =}\NormalTok{ pdata\_wp, }\AttributeTok{model =} \StringTok{"within"}\NormalTok{)}
\FunctionTok{phtest}\NormalTok{(res\_fe\_h, res\_re\_h)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Hausman Test
## 
## data:  lwage ~ expersq + married + union + d81 + d82 + d83 + d84 + d85 +  ...
## chisq = 37.01, df = 10, p-value = 5.637e-05
## alternative hypothesis: one model is inconsistent
\end{verbatim}

\normalsize

\begin{itemize}
\tightlist
\item
  \(p値\) が小さい \(\Rightarrow\) RE仮定を棄却 \(\Rightarrow\) FEを採用
\end{itemize}
\end{frame}

\section{14-3
相関変量効果アプローチ}\label{ux76f8ux95a2ux5909ux91cfux52b9ux679cux30a2ux30d7ux30edux30fcux30c1}

\begin{frame}{CREアプローチの基本アイデア}
\phantomsection\label{creux30a2ux30d7ux30edux30fcux30c1ux306eux57faux672cux30a2ux30a4ux30c7ux30a2}
\begin{itemize}
\tightlist
\item
  \(a_i\) が観測変数と相関することを明示的にモデル化
\item
  \(a_i\) と \(\{x_{it}\}\) の相関を、時間平均 \(\bar{x}_i\)
  との線形関係で表す {[}14.12{]}:
  \[a_i = \alpha + \gamma \bar{x}_i + r_i, \quad \text{Cov}(\bar{x}_i, r_i) = 0\]
\item
  これを元のモデルに代入 {[}14.14{]}:
  \[y_{it} = \alpha + \beta x_{it} + \gamma \bar{x}_i + r_i + u_{it}\]
\item
  \textbf{\(\bar{x}_i\) を追加してRE推定} \(\Rightarrow\)
  \textbf{相関変量効果 (CRE) 推定量}
\end{itemize}
\end{frame}

\begin{frame}{CREとFEの等価性}
\phantomsection\label{creux3068feux306eux7b49ux4fa1ux6027}
\begin{itemize}
\tightlist
\item
  \textbf{重要な結果} {[}14.16{]}: CRE推定量はFE推定量と\textbf{同一}
  \[\hat{\beta}_{CRE} = \hat{\beta}_{FE}\]
\item
  CREアプローチの利点:

  \begin{enumerate}
  \tightlist
  \item
    \textbf{時間不変変数の係数}を推定できる（\(\delta_j\) として）
  \item
    \textbf{RE vs FE 検定}の形式的な枠組みを提供 (\(H_0: \gamma = 0\))
  \item
    不均衡パネルへの拡張が容易
  \end{enumerate}
\end{itemize}
\end{frame}

\begin{frame}[fragile]{CREの推定: WAGEPAN}
\phantomsection\label{creux306eux63a8ux5b9a-wagepan}
\footnotesize

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 時間変動変数の個体平均を計算}
\NormalTok{wagepan}\SpecialCharTok{$}\NormalTok{mean\_expersq }\OtherTok{\textless{}{-}} \FunctionTok{ave}\NormalTok{(wagepan}\SpecialCharTok{$}\NormalTok{expersq, wagepan}\SpecialCharTok{$}\NormalTok{nr)}
\NormalTok{wagepan}\SpecialCharTok{$}\NormalTok{mean\_married }\OtherTok{\textless{}{-}} \FunctionTok{ave}\NormalTok{(wagepan}\SpecialCharTok{$}\NormalTok{married, wagepan}\SpecialCharTok{$}\NormalTok{nr)}
\NormalTok{wagepan}\SpecialCharTok{$}\NormalTok{mean\_union   }\OtherTok{\textless{}{-}} \FunctionTok{ave}\NormalTok{(wagepan}\SpecialCharTok{$}\NormalTok{union, wagepan}\SpecialCharTok{$}\NormalTok{nr)}

\NormalTok{pdata\_wp2 }\OtherTok{\textless{}{-}} \FunctionTok{pdata.frame}\NormalTok{(wagepan, }\AttributeTok{index =} \FunctionTok{c}\NormalTok{(}\StringTok{"nr"}\NormalTok{, }\StringTok{"year"}\NormalTok{))}

\NormalTok{res\_cre }\OtherTok{\textless{}{-}} \FunctionTok{plm}\NormalTok{(lwage }\SpecialCharTok{\textasciitilde{}}\NormalTok{ expersq }\SpecialCharTok{+}\NormalTok{ married }\SpecialCharTok{+}\NormalTok{ union }\SpecialCharTok{+}
\NormalTok{                 mean\_expersq }\SpecialCharTok{+}\NormalTok{ mean\_married }\SpecialCharTok{+}\NormalTok{ mean\_union }\SpecialCharTok{+}
\NormalTok{                 d81 }\SpecialCharTok{+}\NormalTok{ d82 }\SpecialCharTok{+}\NormalTok{ d83 }\SpecialCharTok{+}\NormalTok{ d84 }\SpecialCharTok{+}\NormalTok{ d85 }\SpecialCharTok{+}\NormalTok{ d86 }\SpecialCharTok{+}\NormalTok{ d87,}
               \AttributeTok{data =}\NormalTok{ pdata\_wp2, }\AttributeTok{model =} \StringTok{"random"}\NormalTok{)}
\CommentTok{\# 時間平均変数の係数（γの推定値）}
\FunctionTok{coef}\NormalTok{(res\_cre)[}\FunctionTok{c}\NormalTok{(}\StringTok{"mean\_expersq"}\NormalTok{, }\StringTok{"mean\_married"}\NormalTok{, }\StringTok{"mean\_union"}\NormalTok{)]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## mean_expersq mean_married   mean_union 
##  0.003212666  0.161764098  0.161241547
\end{verbatim}

\normalsize
\end{frame}

\begin{frame}[fragile]{CRE: RE vs FE の検定}
\phantomsection\label{cre-re-vs-fe-ux306eux691cux5b9a}
\begin{itemize}
\tightlist
\item
  \(H_0: \gamma_1 = \gamma_2 = \cdots = \gamma_k = 0\)（REで十分）{[}14.19{]}
\item
  時間平均変数 \(\bar{x}_{i1}, \dots, \bar{x}_{ik}\)
  が全て統計的に有意でなければ RE を採用
\end{itemize}

\footnotesize

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 時間平均変数の結合有意性検定（Wald検定）}
\FunctionTok{library}\NormalTok{(car)}
\FunctionTok{linearHypothesis}\NormalTok{(res\_cre,}
                 \FunctionTok{c}\NormalTok{(}\StringTok{"mean\_expersq = 0"}\NormalTok{,}
                   \StringTok{"mean\_married = 0"}\NormalTok{,}
                   \StringTok{"mean\_union = 0"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Linear hypothesis test:
## mean_expersq = 0
## mean_married = 0
## mean_union = 0
## 
## Model 1: restricted model
## Model 2: lwage ~ expersq + married + union + mean_expersq + mean_married + 
##     mean_union + d81 + d82 + d83 + d84 + d85 + d86 + d87
## 
##   Res.Df Df  Chisq Pr(>Chisq)    
## 1   4349                         
## 2   4346  3 35.992  7.516e-08 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\normalsize
\end{frame}

\section{14-4
パネルデータを用いた政策分析}\label{ux30d1ux30cdux30ebux30c7ux30fcux30bfux3092ux7528ux3044ux305fux653fux7b56ux5206ux6790}

\begin{frame}{一般的な政策分析フレームワーク {[}14.22{]}}
\phantomsection\label{ux4e00ux822cux7684ux306aux653fux7b56ux5206ux6790ux30d5ux30ecux30fcux30e0ux30efux30fcux30af-14.22}
\[y_{it} = \eta_1 + \alpha_2 d2_t + \cdots + \alpha_T dT_t + \beta w_{it} + \mathbf{x}_{it}\boldsymbol{\psi} + a_i + u_{it}\]

\begin{itemize}
\tightlist
\item
  \(w_{it}\): 介入指標（ \(w_{it} = 0\) または \(1\)）
\item
  \(\beta\): 政策効果（関心パラメータ）
\item
  \(\mathbf{x}_{it}\): その他の時変コントロール変数
\item
  FEまたはFDで推定（\(a_i\) と \(w_{it}\) の相関を許容）
\item
  DiD（第13章）は \(T = 2\) の特殊ケース
\end{itemize}
\end{frame}

\begin{frame}{動的効果の推定 {[}14.24{]}}
\phantomsection\label{ux52d5ux7684ux52b9ux679cux306eux63a8ux5b9a-14.24}
\begin{itemize}
\tightlist
\item
  \(t-1\)、\(t-2\) 期までのラグ効果を含む動的モデル:
  \[y_{it} = \eta_1 + \sum_{t=2}^{T}\alpha_t dt_t + \beta_0 w_{it} + \beta_1 w_{i,t-1} + \beta_2 w_{i,t-2} + \mathbf{x}_{it}\boldsymbol{\psi} + a_i + u_{it}\]
\item
  長期効果: \(\beta_0 + \beta_1 + \beta_2\)
\end{itemize}
\end{frame}

\begin{frame}{因果分析の注意点}
\phantomsection\label{ux56e0ux679cux5206ux6790ux306eux6ce8ux610fux70b9}
\begin{itemize}
\tightlist
\item
  \(w_{it}\)
  が過去の誤差項に反応する場合（フィードバック）\(\Rightarrow\)
  厳密外生性違反
\item
  \textbf{検定方法}:
  \(w_{i,t+1}\)（次期の政策）を追加し、有意かどうかを確認 {[}14.25{]}

  \begin{itemize}
  \tightlist
  \item
    有意 \(\Rightarrow\) フィードバックの存在、FE/FDの結果に注意が必要
  \end{itemize}
\item
  \textbf{偽造検定 (Falsification Test)}:
  例えば、今年の介入が去年の成果を予測すべきでない
\end{itemize}
\end{frame}

\begin{frame}{異質トレンドモデル (Heterogeneous Trend Model)
{[}14.26{]}}
\phantomsection\label{ux7570ux8ceaux30c8ux30ecux30f3ux30c9ux30e2ux30c7ux30eb-heterogeneous-trend-model-14.26}
\begin{itemize}
\tightlist
\item
  個体固有の時間トレンド \(g_i t\) が存在する場合:
  \[y_{it} = \eta_1 + \sum_{t=2}^T \alpha_t dt_t + \beta w_{it} + \mathbf{x}_{it}\boldsymbol{\psi} + a_i + g_i t + u_{it}\]
\item
  1階差分で \(a_i\) を除去 \(\Rightarrow\) \(g_i\) が残る {[}14.27{]}:
  \[\Delta y_{it} = \sum_{t=2}^T \alpha_t \Delta dt_t + \beta \Delta w_{it} + \Delta\mathbf{x}_{it}\boldsymbol{\psi} + g_i + \Delta u_{it}\]
\item
  FEを再度適用して \(g_i\) を除去 \(\Rightarrow\) 最低 \(T \geq 3\)
  が必要
\end{itemize}
\end{frame}

\section{14-5
他のデータ構造への応用}\label{ux4ed6ux306eux30c7ux30fcux30bfux69cbux9020ux3078ux306eux5fdcux7528}

\begin{frame}{マッチドペアとクラスターサンプル}
\phantomsection\label{ux30deux30c3ux30c1ux30c9ux30daux30a2ux3068ux30afux30e9ux30b9ux30bfux30fcux30b5ux30f3ux30d7ux30eb}
\begin{itemize}
\tightlist
\item
  パネルデータ手法は\textbf{時間}以外の構造にも応用可能
\item
  \textbf{マッチドペア} (matched pairs): 例) 兄弟・双子ペアの差分

  \begin{itemize}
  \tightlist
  \item
    家族固有効果 \(a_f\) を消去
  \item
    例: 十代妊娠が将来所得に与える影響（姉妹ペア差分）
  \end{itemize}
\item
  \textbf{クラスターサンプル} (cluster sample):
  個体がクラスター（学校、企業）から抽出

  \begin{itemize}
  \tightlist
  \item
    クラスターが「個体」、クラスター内観測が「時点」に対応
  \item
    クラスター効果を固定効果または差分で除去
  \end{itemize}
\end{itemize}
\end{frame}

\begin{frame}{クラスターサンプルにおける注意点}
\phantomsection\label{ux30afux30e9ux30b9ux30bfux30fcux30b5ux30f3ux30d7ux30ebux306bux304aux3051ux308bux6ce8ux610fux70b9}
\begin{itemize}
\tightlist
\item
  政策変数 \(w_{it}\) がクラスター\textbf{内}で変動しない場合（例:
  教師の質の効果） \(\Rightarrow\) 固定効果は使えない \(\Rightarrow\)
  変量効果（または Pooled OLS + クラスター標準誤差）
\item
  クラスターを無視してOLSを使う場合 \(\Rightarrow\)
  標準誤差が過小（過信） \(\Rightarrow\) \textbf{クラスター頑健標準誤差
  (cluster-robust SE)} を使う
\item
  Pooled OLSでクラスター頑健標準誤差を使うことで対処可能
\end{itemize}
\end{frame}

\begin{frame}{クラスター頑健標準誤差の適用場面}
\phantomsection\label{ux30afux30e9ux30b9ux30bfux30fcux9811ux5065ux6a19ux6e96ux8aa4ux5deeux306eux9069ux7528ux5834ux9762}
\begin{itemize}
\tightlist
\item
  クラスタリングが正当化されるのは\textbf{真のクラスターサンプル}の場合

  \begin{itemize}
  \tightlist
  \item
    無作為サンプルをグループに事後分割しても正当化されない
  \end{itemize}
\item
  \textbf{政策変数がグループレベルで変化する場合}（例: 最低賃金法）

  \begin{itemize}
  \tightlist
  \item
    処置の割り当て不確実性を考慮するためクラスタリングが適切
  \end{itemize}
\end{itemize}
\end{frame}

\section{まとめ}\label{ux307eux3068ux3081}

\begin{frame}{第14章のまとめ}
\phantomsection\label{ux7b2c14ux7ae0ux306eux307eux3068ux3081}
\begin{longtable}[]{@{}llll@{}}
\toprule\noalign{}
手法 & \(a_i\) と \(x_{it}\) の相関 & 時間不変変数 & 効率性 \\
\midrule\noalign{}
\endhead
Pooled OLS & 不可 & 推定可 & 低 \\
固定効果 (FE) & 許容 & 推定不可 & 中 \\
1階差分 (FD) & 許容 & 推定不可 & 中 \\
変量効果 (RE) & 不可（仮定） & 推定可 & 高 \\
相関変量効果 (CRE) & 許容 & 推定可 & 中 \\
\bottomrule\noalign{}
\end{longtable}
\end{frame}

\begin{frame}{まとめ（続き）}
\phantomsection\label{ux307eux3068ux3081ux7d9aux304d}
\begin{itemize}
\tightlist
\item
  \textbf{FE vs FD}: \(u_{it}\) が系列無相関 \(\Rightarrow\)
  FE優位；ランダムウォーク \(\Rightarrow\) FD優位
\item
  \textbf{RE vs FE}: Hausman検定または CRE アプローチで選択
\item
  \textbf{CRE}: FE の点推定を維持しつつ、時間不変変数の係数と RE vs FE
  の検定を提供
\item
  \textbf{政策分析}: 処置指標を適切に定義すれば DiD
  はFEの特殊ケース；動的効果・フィードバック検定も重要
\item
  \textbf{他のデータ構造}:
  兄弟ペア、クラスターサンプルにも同様の手法が適用可能
\end{itemize}
\end{frame}

\end{document}
