% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
  ignorenonframetext,
]{beamer}
\newif\ifbibliography
\usepackage{pgfpages}
\setbeamertemplate{caption}[numbered]
\setbeamertemplate{caption label separator}{: }
\setbeamercolor{caption name}{fg=normal text.fg}
\beamertemplatenavigationsymbolsempty
% remove section numbering
\setbeamertemplate{part page}{
  \centering
  \begin{beamercolorbox}[sep=16pt,center]{part title}
    \usebeamerfont{part title}\insertpart\par
  \end{beamercolorbox}
}
\setbeamertemplate{section page}{
  \centering
  \begin{beamercolorbox}[sep=12pt,center]{section title}
    \usebeamerfont{section title}\insertsection\par
  \end{beamercolorbox}
}
\setbeamertemplate{subsection page}{
  \centering
  \begin{beamercolorbox}[sep=8pt,center]{subsection title}
    \usebeamerfont{subsection title}\insertsubsection\par
  \end{beamercolorbox}
}
% Prevent slide breaks in the middle of a paragraph
\widowpenalties 1 10000
\raggedbottom
\AtBeginPart{
  \frame{\partpage}
}
\AtBeginSection{
  \ifbibliography
  \else
    \frame{\sectionpage}
  \fi
}
\AtBeginSubsection{
  \frame{\subsectionpage}
}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\usetheme[]{Montpellier}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
\usepackage{caption}
% Make caption package work with longtable
\makeatletter
\def\fnum@table{\tablename~\thetable}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
%\documentclass[unicode,10pt]{beamer}% 'unicode'が必要
\usepackage{luatexja}% 日本語を使う場合は必須
%\usepackage[japanese]{babel}	
%\usefonttheme[onlymath]{serif}
%\usepackage[T1]{fontenc} %これを使うと、ギリシャ文字が出ない
%\usepackage{textcomp}
%\usepackage[scale=1.0]{tgheros} % Sans serif font
%\usepackage[scaled]{beramono} % Monospace font
%\usepackage{luatexja-otf}
%\renewcommand{\kanjifamilydefault}{\gtdefault}
%\usepackage[haranoaji]{luatexja-preset}

% スライド番号の表示 %%%%%%%%%%%%%%%%%%%
\makeatletter
\setbeamertemplate{footline}{%
  \leavevmode%
  \hbox{%
  \begin{beamercolorbox}[wd=.5\paperwidth,ht=2.25ex,dp=1ex,right]{date in head/foot}%
    \insertframenumber{} \hspace*{2ex} % new version without total frames
  \end{beamercolorbox}}%
  \vskip0pt%
}
\makeatother
% スライド番号の表示 %%%%%%%%%%%%%%%%%%%
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{第15章: 操作変数法と二段階最小二乗法}
\subtitle{Jeffrey Wooldridge (2016).\\
Introductory Econometrics: A Modern Approach\\
Seventh Edition. Cengage Learning.}
\author{}
\date{\vspace{-2.5em}2026-03-08}

\begin{document}
\frame{\titlepage}

\section{準備}\label{ux6e96ux5099}

\begin{frame}[fragile]{必要なパッケージの読み込み}
\phantomsection\label{ux5fc5ux8981ux306aux30d1ux30c3ux30b1ux30fcux30b8ux306eux8aadux307fux8fbcux307f}
\begin{itemize}
\tightlist
\item
  \texttt{wooldridge}: データセット
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(wooldridge)}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  \texttt{AER}: 操作変数推定 \texttt{ivreg()}
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{install.packages}\NormalTok{(}\StringTok{"AER"}\NormalTok{)}
\FunctionTok{library}\NormalTok{(AER)}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  \texttt{car}: 線形仮説検定 \texttt{linearHypothesis()}
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(car)}
\end{Highlighting}
\end{Shaded}
\end{frame}

\section{15-1 動機:
省略変数と操作変数}\label{ux52d5ux6a5f-ux7701ux7565ux5909ux6570ux3068ux64cdux4f5cux5909ux6570}

\begin{frame}{内生変数問題の背景}
\phantomsection\label{ux5185ux751fux5909ux6570ux554fux984cux306eux80ccux666f}
\begin{itemize}
\tightlist
\item
  これまでの対処法:

  \begin{enumerate}
  \tightlist
  \item
    省略変数バイアスを無視（不偏性・一致性を失う）
  \item
    代理変数の利用（第9章）
  \item
    固定効果・1階差分（第13・14章）：\textbf{時間不変の}省略変数のみ対処可能
  \end{enumerate}
\item
  本章では別のアプローチ：\textbf{操作変数法 (Instrumental Variables,
  IV)}

  \begin{itemize}
  \tightlist
  \item
    時変の省略変数・測定誤差にも対処可能
  \item
    応用計量経済学でOLSに次ぐ最重要手法
  \end{itemize}
\end{itemize}
\end{frame}

\begin{frame}{単純回帰モデルでの問題設定}
\phantomsection\label{ux5358ux7d14ux56deux5e30ux30e2ux30c7ux30ebux3067ux306eux554fux984cux8a2dux5b9a}
\begin{itemize}
\tightlist
\item
  モデル {[}15.1{]}: \[\log(wage) = \beta_0 + \beta_1 educ + u\]
\item
  \(u\) には観察不能な能力 (\(abil\)) が含まれる
\item
  \(\text{Cov}(educ, u) \neq 0\) \(\Rightarrow\) OLSは不一致
\item
  必要なのは \(educ\) の\textbf{操作変数} \(z\)
\end{itemize}
\end{frame}

\begin{frame}{操作変数 (Instrumental Variable) の条件}
\phantomsection\label{ux64cdux4f5cux5909ux6570-instrumental-variable-ux306eux6761ux4ef6}
変数 \(z\) が \(x\) の操作変数になるための2条件:

\begin{enumerate}
\item
  \textbf{操作変数の外生性 (Instrument Exogeneity)} {[}15.4{]}:
  \[\text{Cov}(z, u) = 0\] \(z\) は誤差項と無相関（検定不可能:
  経済理論で正当化）
\item
  \textbf{操作変数の関連性 (Instrument Relevance)} {[}15.5{]}:
  \[\text{Cov}(z, x) \neq 0\] \(z\) は内生変数 \(x\) と相関（検定可能:
  第1段階回帰）
\end{enumerate}
\end{frame}

\begin{frame}[fragile]{操作変数の候補例（賃金方程式）}
\phantomsection\label{ux64cdux4f5cux5909ux6570ux306eux5019ux88dcux4f8bux8cc3ux91d1ux65b9ux7a0bux5f0f}
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3333}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3333}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3333}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
IV候補
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
外生性
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
関連性
\end{minipage} \\
\midrule\noalign{}
\endhead
父親の教育年数 (\texttt{fatheduc}) &
ある程度成立（能力との無相関を仮定） &
\texttt{educ}と正相関（検定可能） \\
兄弟の数 (\texttt{sibs}) & 成立しやすい（能力との無相関） &
\texttt{educ}と負相関（検定可能） \\
誕生四半期 (\texttt{frstqrt}) & 主張される（季節と能力は無関係） &
わずかな相関（問題あり） \\
IQ & 外生性を欠く（abilの代理変数） & --- \\
\bottomrule\noalign{}
\end{longtable}
\end{frame}

\begin{frame}{IV推定量の導出}
\phantomsection\label{ivux63a8ux5b9aux91cfux306eux5c0eux51fa}
\begin{itemize}
\tightlist
\item
  母集団の共分散より:
  \[\text{Cov}(z, y) = \beta_1 \text{Cov}(z, x) + \text{Cov}(z, u)\]
\item
  \(\text{Cov}(z, u) = 0\) のとき、\(\beta_1\) を\textbf{識別}
  (identify) できる {[}15.9{]}:
  \[\beta_1 = \frac{\text{Cov}(z, y)}{\text{Cov}(z, x)}\]
\item
  標本対応の\textbf{IV推定量} {[}15.10{]}:
  \[\hat{\beta}_1^{IV} = \frac{\sum_{i=1}^n (z_i - \bar{z})(y_i - \bar{y})}{\sum_{i=1}^n (z_i - \bar{z})(x_i - \bar{x})}\]
\end{itemize}
\end{frame}

\begin{frame}{IV推定量の性質}
\phantomsection\label{ivux63a8ux5b9aux91cfux306eux6027ux8cea}
\begin{itemize}
\tightlist
\item
  \textbf{一致性}:
  \(\text{plim}(\hat{\beta}_1^{IV}) = \beta_1\)（両条件が成立するとき）
\item
  \textbf{不偏性なし}:
  IV推定量は小標本では不偏でない（大標本が望ましい）
\item
  \textbf{漸近分散} {[}15.12{]}:
  \[\text{AsyVar}(\hat{\beta}_1^{IV}) = \frac{\sigma^2}{n \sigma_x^2 \rho_{x,z}^2}\]
  ここで \(\rho_{x,z}^2\) は \(x\) と \(z\) の相関の二乗
\item
  OLS分散 \(= \sigma^2 / (n\sigma_x^2)\)
  より常に大きい（\(\rho_{x,z}^2 \leq 1\)）
\item
  \(\rho_{x,z}^2\) が小さいほど IV の分散は巨大に \(\Rightarrow\)
  \textbf{弱い操作変数問題}
\end{itemize}
\end{frame}

\section{15-1a
IV推定量の統計的推論}\label{a-ivux63a8ux5b9aux91cfux306eux7d71ux8a08ux7684ux63a8ux8ad6}

\begin{frame}[fragile]{例15.1: 既婚女性の教育収益率 (MROZ)}
\phantomsection\label{ux4f8b15.1-ux65e2ux5a5aux5973ux6027ux306eux6559ux80b2ux53ceux76caux7387-mroz}
\begin{itemize}
\tightlist
\item
  データ: 既婚女性428人（就業者のみ）
\item
  モデル: \(\log(wage) = \beta_0 + \beta_1 educ + u\)
\item
  IV: \(fatheduc\)（父親の教育年数）→ 関連性: 有（検定可）、外生性: 仮定
\end{itemize}

\footnotesize

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(mroz)}
\NormalTok{mroz\_work }\OtherTok{\textless{}{-}} \FunctionTok{subset}\NormalTok{(mroz, inlf }\SpecialCharTok{==} \DecValTok{1}\NormalTok{)  }\CommentTok{\# 就業者428人}

\CommentTok{\# 第1段階: educとfatheducの関連性確認}
\NormalTok{first\_rel }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(educ }\SpecialCharTok{\textasciitilde{}}\NormalTok{ fatheduc, }\AttributeTok{data =}\NormalTok{ mroz\_work)}
\FunctionTok{coef}\NormalTok{(}\FunctionTok{summary}\NormalTok{(first\_rel))[}\StringTok{"fatheduc"}\NormalTok{, ]  }\CommentTok{\# t = 9.28}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     Estimate   Std. Error      t value     Pr(>|t|) 
## 2.694416e-01 2.858634e-02 9.425538e+00 2.764936e-19
\end{verbatim}

\normalsize
\end{frame}

\begin{frame}[fragile]{例15.1: OLS vs IV の比較}
\phantomsection\label{ux4f8b15.1-ols-vs-iv-ux306eux6bd4ux8f03}
\footnotesize

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# OLS}
\NormalTok{res\_ols151 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(lwage }\SpecialCharTok{\textasciitilde{}}\NormalTok{ educ, }\AttributeTok{data =}\NormalTok{ mroz\_work)}
\CommentTok{\# IV (fatheduc を educ の操作変数として使用)}
\NormalTok{res\_iv151 }\OtherTok{\textless{}{-}} \FunctionTok{ivreg}\NormalTok{(lwage }\SpecialCharTok{\textasciitilde{}}\NormalTok{ educ }\SpecialCharTok{|}\NormalTok{ fatheduc, }\AttributeTok{data =}\NormalTok{ mroz\_work)}

\FunctionTok{rbind}\NormalTok{(}
  \AttributeTok{OLS =} \FunctionTok{coef}\NormalTok{(}\FunctionTok{summary}\NormalTok{(res\_ols151))[}\StringTok{"educ"}\NormalTok{, }\DecValTok{1}\SpecialCharTok{:}\DecValTok{2}\NormalTok{],}
  \AttributeTok{IV  =} \FunctionTok{coef}\NormalTok{(}\FunctionTok{summary}\NormalTok{(res\_iv151))[}\StringTok{"educ"}\NormalTok{, }\DecValTok{1}\SpecialCharTok{:}\DecValTok{2}\NormalTok{]}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       Estimate Std. Error
## OLS 0.10864866 0.01439985
## IV  0.05917348 0.03514177
\end{verbatim}

\normalsize

\begin{itemize}
\tightlist
\item
  OLS: \(\hat{\beta}_{educ} \approx 0.109\) (se = 0.014)
\item
  IV: \(\hat{\beta}_{educ} \approx 0.059\) (se = 0.035)
\item
  IV標準誤差はOLSの約2.5倍 \(\Rightarrow\) 信頼区間がOLS推定値を含む
\end{itemize}
\end{frame}

\begin{frame}[fragile]{例15.2: 男性の教育収益率 (WAGE2)}
\phantomsection\label{ux4f8b15.2-ux7537ux6027ux306eux6559ux80b2ux53ceux76caux7387-wage2}
\begin{itemize}
\tightlist
\item
  IV: \(sibs\)（兄弟姉妹数）--- 能力と無相関と仮定
\end{itemize}

\footnotesize

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(wage2)}
\CommentTok{\# 関連性確認}
\FunctionTok{lm}\NormalTok{(educ }\SpecialCharTok{\textasciitilde{}}\NormalTok{ sibs, }\AttributeTok{data =}\NormalTok{ wage2)}\SpecialCharTok{$}\NormalTok{coef[}\StringTok{"sibs"}\NormalTok{]  }\CommentTok{\# 負の係数: 有意}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       sibs 
## -0.2279164
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# OLS vs IV}
\NormalTok{res\_ols152 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(lwage }\SpecialCharTok{\textasciitilde{}}\NormalTok{ educ, }\AttributeTok{data =}\NormalTok{ wage2)}
\NormalTok{res\_iv152  }\OtherTok{\textless{}{-}} \FunctionTok{ivreg}\NormalTok{(lwage }\SpecialCharTok{\textasciitilde{}}\NormalTok{ educ }\SpecialCharTok{|}\NormalTok{ sibs, }\AttributeTok{data =}\NormalTok{ wage2)}
\FunctionTok{rbind}\NormalTok{(}
  \AttributeTok{OLS =} \FunctionTok{coef}\NormalTok{(}\FunctionTok{summary}\NormalTok{(res\_ols152))[}\StringTok{"educ"}\NormalTok{, }\DecValTok{1}\SpecialCharTok{:}\DecValTok{2}\NormalTok{],}
  \AttributeTok{IV  =} \FunctionTok{coef}\NormalTok{(}\FunctionTok{summary}\NormalTok{(res\_iv152))[}\StringTok{"educ"}\NormalTok{, }\DecValTok{1}\SpecialCharTok{:}\DecValTok{2}\NormalTok{]}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      Estimate  Std. Error
## OLS 0.0598392 0.005963094
## IV  0.1224326 0.026350568
\end{verbatim}

\normalsize

\begin{itemize}
\tightlist
\item
  IV推定値 (\(\approx 0.122\)) はOLS (\(\approx 0.059\)) より大きい
\end{itemize}
\end{frame}

\section{15-1b
弱い操作変数の問題}\label{b-ux5f31ux3044ux64cdux4f5cux5909ux6570ux306eux554fux984c}

\begin{frame}{不良操作変数の漸近バイアス {[}15.19{]}}
\phantomsection\label{ux4e0dux826fux64cdux4f5cux5909ux6570ux306eux6f38ux8fd1ux30d0ux30a4ux30a2ux30b9-15.19}
\[\text{plim}\, \hat{\beta}_1^{IV} = \beta_1 + \frac{\text{Corr}(z, u)}{\text{Corr}(z, x)} \cdot \frac{\sigma_u}{\sigma_x}\]

\begin{itemize}
\tightlist
\item
  外生性 \(\text{Cov}(z, u) = 0\) が成立 \(\Rightarrow\) IV は一致推定
\item
  \(\text{Corr}(z, x)\) が小さいとき: \(\text{Corr}(z, u)\)
  がわずかでも不一致が巨大
\item
  OLSのバイアス {[}15.20{]}:
  \[\text{plim}\, \hat{\beta}_1^{OLS} = \beta_1 + \text{Corr}(x, u) \cdot \frac{\sigma_u}{\sigma_x}\]
\item
  \textbf{IV が OLS より悪い可能性}: \(\text{Corr}(z, u)\) が小さくとも
  \(\text{Corr}(z, x)\) が非常に小さければ IV の不一致は OLS
  より大きくなりうる
\end{itemize}
\end{frame}

\begin{frame}[fragile]{例15.3: 喫煙と出生時体重 (BWGHT) ---
悪い操作変数}
\phantomsection\label{ux4f8b15.3-ux55abux7159ux3068ux51faux751fux6642ux4f53ux91cd-bwght-ux60aaux3044ux64cdux4f5cux5909ux6570}
\begin{itemize}
\tightlist
\item
  IV候補: \(cigprice\)（タバコ価格）→ \(packs\) の関連性が皆無
\end{itemize}

\footnotesize

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(bwght)}
\CommentTok{\# 関連性確認: packs と cigprice は相関しているか}
\FunctionTok{lm}\NormalTok{(packs }\SpecialCharTok{\textasciitilde{}}\NormalTok{ cigprice, }\AttributeTok{data =}\NormalTok{ bwght)}\SpecialCharTok{$}\NormalTok{coef[}\StringTok{"cigprice"}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     cigprice 
## 0.0002828844
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# → ほぼゼロ: cigprice は packs の有効な IV ではない}
\CommentTok{\# （関連性条件 [15.5] を満たさない）}
\end{Highlighting}
\end{Shaded}

\normalsize

\begin{itemize}
\tightlist
\item
  \textbf{結論}: 操作変数候補は必ず\textbf{関連性}を統計的に確認すること
\item
  関連性がない場合、IV推定値は意味をなさない
\end{itemize}
\end{frame}

\section{15-2
重回帰モデルへのIV拡張}\label{ux91cdux56deux5e30ux30e2ux30c7ux30ebux3078ux306eivux62e1ux5f35}

\begin{frame}{構造方程式と外生変数・内生変数}
\phantomsection\label{ux69cbux9020ux65b9ux7a0bux5f0fux3068ux5916ux751fux5909ux6570ux5185ux751fux5909ux6570}
\begin{itemize}
\tightlist
\item
  \textbf{構造方程式 (structural equation)} {[}15.22{]}:
  \[y_1 = \beta_0 + \beta_1 y_2 + \beta_2 z_1 + u_1\]

  \begin{itemize}
  \tightlist
  \item
    \(y_2\): \textbf{内生的説明変数} (\(\text{Cov}(y_2, u_1) \neq 0\))
  \item
    \(z_1\): \textbf{外生変数}
    (\(\text{Cov}(z_1, u_1) = 0\)）\(\Rightarrow\) 自身の操作変数
  \end{itemize}
\item
  \(z_1\) は構造方程式に含まれるため \(y_2\) の IV に使えない
  \(\Rightarrow\) 追加の外生変数 \(z_2\) が必要
\item
  \textbf{除外制約 (exclusion restriction)}: \(z_2\)
  は構造方程式に現れず外生
\end{itemize}
\end{frame}

\begin{frame}{誘導型方程式と識別条件}
\phantomsection\label{ux8a98ux5c0eux578bux65b9ux7a0bux5f0fux3068ux8b58ux5225ux6761ux4ef6}
\begin{itemize}
\tightlist
\item
  \(y_2\) の誘導型 (reduced form) {[}15.26{]}:
  \[y_2 = \pi_0 + \pi_1 z_1 + \pi_2 z_2 + v_2\]
\item
  識別条件 {[}15.27{]}: \(\pi_2 \neq 0\)（\(z_2\) が \(y_2\)
  と偏相関を持つ）
\item
  一般化: 構造方程式 {[}15.28{]} に \(k-1\)
  個の外生変数と1個の内生変数がある場合

  \begin{itemize}
  \tightlist
  \item
    誘導型 {[}15.30{]} で \(z_k\) の係数 \(\pi_k \neq 0\) が識別条件
  \end{itemize}
\end{itemize}
\end{frame}

\begin{frame}[fragile]{例15.4: 大学近接性を教育のIVとして使用 (CARD)}
\phantomsection\label{ux4f8b15.4-ux5927ux5b66ux8fd1ux63a5ux6027ux3092ux6559ux80b2ux306eivux3068ux3057ux3066ux4f7fux7528-card}
\begin{itemize}
\tightlist
\item
  IV: \(nearc4\)（4年制大学近辺で育ったか）、カード (1995)
\end{itemize}

\scriptsize

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(card)}
\CommentTok{\# OLS}
\NormalTok{res\_ols154 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(lwage }\SpecialCharTok{\textasciitilde{}}\NormalTok{ educ }\SpecialCharTok{+}\NormalTok{ exper }\SpecialCharTok{+}\NormalTok{ expersq }\SpecialCharTok{+}\NormalTok{ black }\SpecialCharTok{+}\NormalTok{ smsa }\SpecialCharTok{+}\NormalTok{ south,}
                 \AttributeTok{data =}\NormalTok{ card)}
\CommentTok{\# 2SLS (nearc4 を educ の操作変数として使用)}
\NormalTok{res\_iv154 }\OtherTok{\textless{}{-}} \FunctionTok{ivreg}\NormalTok{(lwage }\SpecialCharTok{\textasciitilde{}}\NormalTok{ educ }\SpecialCharTok{+}\NormalTok{ exper }\SpecialCharTok{+}\NormalTok{ expersq }\SpecialCharTok{+}\NormalTok{ black }\SpecialCharTok{+}\NormalTok{ smsa }\SpecialCharTok{+}\NormalTok{ south }\SpecialCharTok{|}
\NormalTok{                     nearc4 }\SpecialCharTok{+}\NormalTok{ exper }\SpecialCharTok{+}\NormalTok{ expersq }\SpecialCharTok{+}\NormalTok{ black }\SpecialCharTok{+}\NormalTok{ smsa }\SpecialCharTok{+}\NormalTok{ south,}
                   \AttributeTok{data =}\NormalTok{ card)}
\FunctionTok{rbind}\NormalTok{(}
  \AttributeTok{OLS =} \FunctionTok{coef}\NormalTok{(}\FunctionTok{summary}\NormalTok{(res\_ols154))[}\StringTok{"educ"}\NormalTok{, }\DecValTok{1}\SpecialCharTok{:}\DecValTok{2}\NormalTok{],}
  \AttributeTok{IV  =} \FunctionTok{coef}\NormalTok{(}\FunctionTok{summary}\NormalTok{(res\_iv154))[}\StringTok{"educ"}\NormalTok{, }\DecValTok{1}\SpecialCharTok{:}\DecValTok{2}\NormalTok{]}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       Estimate  Std. Error
## OLS 0.07400899 0.003505435
## IV  0.13228884 0.049233236
\end{verbatim}

\normalsize
\end{frame}

\begin{frame}{例15.4: 結果の解釈}
\phantomsection\label{ux4f8b15.4-ux7d50ux679cux306eux89e3ux91c8}
\begin{itemize}
\tightlist
\item
  OLS: \(\hat{\beta}_{educ} \approx 0.075\) (se = 0.003)
\item
  IV: \(\hat{\beta}_{educ} \approx 0.132\) (se = 0.055)（Table
  15.1に近似）
\item
  IV推定値はOLSの約1.8倍 \(\Rightarrow\) OLSの下方バイアスと整合的
\item
  IV標準誤差はOLSの約18倍 \(\Rightarrow\) 95\%信頼区間が非常に広い
\item
  第1段階での \(nearc4\) の \(t\) 値 \(\approx 3.64\)（有意）
\end{itemize}
\end{frame}

\section{15-3 二段階最小二乗法
(2SLS)}\label{ux4e8cux6bb5ux968eux6700ux5c0fux4e8cux4e57ux6cd5-2sls}

\begin{frame}{2SLSのアイデア: 複数の操作変数}
\phantomsection\label{slsux306eux30a2ux30a4ux30c7ux30a2-ux8907ux6570ux306eux64cdux4f5cux5909ux6570}
\begin{itemize}
\tightlist
\item
  内生変数 \(y_2\) に対して複数の除外変数 \(z_2, z_3\) がある場合
\item
  それぞれ単独で使えるが、最適な線形結合を使う \(\Rightarrow\)
  \textbf{2SLS}
\item
  \textbf{第1段階} (First Stage): \(y_2\) を全外生変数に回帰して fitted
  values \(\hat{y}_2\) を得る {[}15.36{]}:
  \[\hat{y}_2 = \hat{\pi}_0 + \hat{\pi}_1 z_1 + \hat{\pi}_2 z_2 + \hat{\pi}_3 z_3\]
\item
  \textbf{第2段階} (Second Stage): \(y_1\) を \(\hat{y}_2\) と \(z_1\)
  に回帰 {[}15.38{]}: \[y_1 \text{ on } \hat{y}_2 \text{ and } z_1\]
\item
  2SLSの標準誤差は専用コマンドで計算すること（手動計算は標準誤差が不正確）
\end{itemize}
\end{frame}

\begin{frame}[fragile]{例15.5: 既婚女性の教育収益率 (MROZ) --- 2SLS}
\phantomsection\label{ux4f8b15.5-ux65e2ux5a5aux5973ux6027ux306eux6559ux80b2ux53ceux76caux7387-mroz-2sls}
\begin{itemize}
\tightlist
\item
  除外IV: \(motheduc\), \(fatheduc\)（両親の教育年数）
\item
  まず: 両親の教育が \(educ\) と偏相関を持つか確認（\(F\) 検定）
\end{itemize}

\scriptsize

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{first\_stage155 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(educ }\SpecialCharTok{\textasciitilde{}}\NormalTok{ motheduc }\SpecialCharTok{+}\NormalTok{ fatheduc }\SpecialCharTok{+}\NormalTok{ exper }\SpecialCharTok{+}\NormalTok{ expersq,}
                     \AttributeTok{data =}\NormalTok{ mroz\_work)}
\CommentTok{\# 除外変数の結合有意性 (F統計量 \textgreater{} 10 が目安)}
\FunctionTok{linearHypothesis}\NormalTok{(first\_stage155, }\FunctionTok{c}\NormalTok{(}\StringTok{"motheduc = 0"}\NormalTok{, }\StringTok{"fatheduc = 0"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Linear hypothesis test:
## motheduc = 0
## fatheduc = 0
## 
## Model 1: restricted model
## Model 2: educ ~ motheduc + fatheduc + exper + expersq
## 
##   Res.Df    RSS Df Sum of Sq    F    Pr(>F)    
## 1    425 2219.2                                
## 2    423 1758.6  2    460.64 55.4 < 2.2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\normalsize
\end{frame}

\begin{frame}[fragile]{例15.5: 2SLS推定}
\phantomsection\label{ux4f8b15.5-2slsux63a8ux5b9a}
\footnotesize

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{res\_2sls155 }\OtherTok{\textless{}{-}} \FunctionTok{ivreg}\NormalTok{(lwage }\SpecialCharTok{\textasciitilde{}}\NormalTok{ educ }\SpecialCharTok{+}\NormalTok{ exper }\SpecialCharTok{+}\NormalTok{ expersq }\SpecialCharTok{|}
\NormalTok{                       motheduc }\SpecialCharTok{+}\NormalTok{ fatheduc }\SpecialCharTok{+}\NormalTok{ exper }\SpecialCharTok{+}\NormalTok{ expersq,}
                     \AttributeTok{data =}\NormalTok{ mroz\_work)}
\FunctionTok{summary}\NormalTok{(res\_2sls155)}\SpecialCharTok{$}\NormalTok{coefficients[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{4}\NormalTok{, ]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                  Estimate   Std. Error    t value    Pr(>|t|)
## (Intercept)  0.0481003069 0.4003280776  0.1201522 0.904419479
## educ         0.0613966287 0.0314366956  1.9530242 0.051474174
## exper        0.0441703929 0.0134324755  3.2883286 0.001091838
## expersq     -0.0008989696 0.0004016856 -2.2379930 0.025740027
\end{verbatim}

\normalsize

\begin{itemize}
\tightlist
\item
  \(\hat{\beta}_{educ} \approx 0.061\) (se =
  0.031)、5\%水準でぎりぎり有意
\item
  OLS (\(\approx 0.108\)) より低い \(\Rightarrow\) 能力バイアスと整合的
\end{itemize}
\end{frame}

\section{15-3c
弱い操作変数の検出}\label{c-ux5f31ux3044ux64cdux4f5cux5909ux6570ux306eux691cux51fa}

\begin{frame}[fragile]{Stock-Yogo (2005) の弱操作変数検定}
\phantomsection\label{stock-yogo-2005-ux306eux5f31ux64cdux4f5cux5909ux6570ux691cux5b9a}
\begin{itemize}
\tightlist
\item
  IV推定量は関連性が低い場合、\textbf{大標本でも深刻なバイアス}
\item
  \textbf{実用的な基準} (Stock-Yogo, 2005):

  \begin{itemize}
  \tightlist
  \item
    操作変数が1つ: 第1段階の \(t\) 値 \(> \sqrt{10} \approx 3.2\)
  \item
    操作変数が複数: 第1段階の除外変数の \(F\) 値 \(> 10\)
  \end{itemize}
\item
  より厳密には \(F > 20\)（Olea and Pflueger, 2013）という主張も
\end{itemize}

\scriptsize

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 例15.5の第1段階F統計量}
\NormalTok{ht }\OtherTok{\textless{}{-}} \FunctionTok{linearHypothesis}\NormalTok{(first\_stage155, }\FunctionTok{c}\NormalTok{(}\StringTok{"motheduc = 0"}\NormalTok{, }\StringTok{"fatheduc = 0"}\NormalTok{))}
\FunctionTok{cat}\NormalTok{(}\StringTok{"F統計量:"}\NormalTok{, ht}\SpecialCharTok{$}\NormalTok{F[}\DecValTok{2}\NormalTok{], }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)  }\CommentTok{\# \textgreater{}\textgreater{} 10 → 弱い操作変数問題なし}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## F統計量: 55.4003
\end{verbatim}

\normalsize
\end{frame}

\begin{frame}{次数条件と階数条件}
\phantomsection\label{ux6b21ux6570ux6761ux4ef6ux3068ux968eux6570ux6761ux4ef6}
\begin{itemize}
\tightlist
\item
  \textbf{次数条件 (Order Condition)}: 除外された外生変数の数 \(\geq\)
  内生変数の数

  \begin{itemize}
  \tightlist
  \item
    ちょうど識別 (just-identified): 除外IV数 = 内生変数数
  \item
    過剰識別 (over-identified): 除外IV数 \textgreater{} 内生変数数
    \(\Rightarrow\) 検定可能
  \end{itemize}
\item
  \textbf{階数条件 (Rank Condition)}:
  各内生変数に対して少なくとも1つの除外変数が部分相関を持つ

  \begin{itemize}
  \tightlist
  \item
    実質的に重要: 各内生変数の誘導型回帰で除外IVが有意かを確認
  \end{itemize}
\end{itemize}
\end{frame}

\section{15-4
測定誤差問題へのIV応用}\label{ux6e2cux5b9aux8aa4ux5deeux554fux984cux3078ux306eivux5fdcux7528}

\begin{frame}{古典的測定誤差とIV}
\phantomsection\label{ux53e4ux5178ux7684ux6e2cux5b9aux8aa4ux5deeux3068iv}
\begin{itemize}
\tightlist
\item
  古典的測定誤差モデル {[}15.45, 15.46{]}:
  \[y = \beta_0 + \beta_1 x_1^* + \beta_2 x_2 + u\]
  \[x_1 = x_1^* + e_1 \quad \Rightarrow \quad \text{OLSバイアス（ゼロ方向）}\]
\item
  解決策: \(x_1^*\) の別の測定値 \(z_1\) を IV として使用

  \begin{itemize}
  \tightlist
  \item
    \(z_1 = x_1^* + a_1\)（異なる測定誤差 \(a_1\)）
  \item
    \(e_1\) と \(a_1\) が無相関なら \(z_1\) は有効な IV
  \end{itemize}
\end{itemize}
\end{frame}

\begin{frame}[fragile]{例15.6: 能力の指標としての2つのテストスコア
(WAGE2)}
\phantomsection\label{ux4f8b15.6-ux80fdux529bux306eux6307ux6a19ux3068ux3057ux3066ux306e2ux3064ux306eux30c6ux30b9ux30c8ux30b9ux30b3ux30a2-wage2}
\begin{itemize}
\tightlist
\item
  \(IQ\)（第1テスト）と \(KWW\)（第2テスト）を能力の2測定値として使用
\item
  \(IQ\) を含む方程式を推定し、\(KWW\) を \(IQ\) の IV として使用
\end{itemize}

\footnotesize

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{res\_iv156 }\OtherTok{\textless{}{-}} \FunctionTok{ivreg}\NormalTok{(lwage }\SpecialCharTok{\textasciitilde{}}\NormalTok{ educ }\SpecialCharTok{+}\NormalTok{ exper }\SpecialCharTok{+}\NormalTok{ tenure }\SpecialCharTok{+}\NormalTok{ married }\SpecialCharTok{+}
\NormalTok{                     south }\SpecialCharTok{+}\NormalTok{ urban }\SpecialCharTok{+}\NormalTok{ black }\SpecialCharTok{+}\NormalTok{ IQ }\SpecialCharTok{|}
\NormalTok{                     KWW }\SpecialCharTok{+}\NormalTok{ exper }\SpecialCharTok{+}\NormalTok{ tenure }\SpecialCharTok{+}\NormalTok{ married }\SpecialCharTok{+}
\NormalTok{                     south }\SpecialCharTok{+}\NormalTok{ urban }\SpecialCharTok{+}\NormalTok{ black,}
                   \AttributeTok{data =}\NormalTok{ wage2)}
\FunctionTok{coef}\NormalTok{(}\FunctionTok{summary}\NormalTok{(res\_iv156))[}\StringTok{"educ"}\NormalTok{, ]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     Estimate   Std. Error      t value     Pr(>|t|) 
## 1.034136e-01 1.543919e-02 6.698122e+00 3.656739e-11
\end{verbatim}

\normalsize

\begin{itemize}
\tightlist
\item
  \(\hat{\beta}_{educ} \approx 0.025\)（se = 0.017）: 非有意
  \(\Rightarrow\) 測定誤差の相関が疑われる
\end{itemize}
\end{frame}

\section{15-5
内生性検定と過剰識別制約の検定}\label{ux5185ux751fux6027ux691cux5b9aux3068ux904eux5270ux8b58ux5225ux5236ux7d04ux306eux691cux5b9a}

\begin{frame}[fragile]{15-5a 内生性検定}
\phantomsection\label{a-ux5185ux751fux6027ux691cux5b9a}
\begin{itemize}
\tightlist
\item
  2SLSはOLSより標準誤差が大きい \(\Rightarrow\)
  本当に内生性があるか確認したい
\item
  \textbf{Hausman型の内生性検定}（回帰ベース）手順:
\end{itemize}

\begin{enumerate}
[(i)]
\item
  誘導型で \(y_2\) を全外生変数に回帰し残差 \(\hat{v}_2\) を得る
\item
  構造方程式に \(\hat{v}_2\) を追加してOLS推定
\item
  \(\hat{v}_2\) の係数が有意 \(\Rightarrow\) \(y_2\) は内生的
\end{enumerate}

\scriptsize

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Step 1: 誘導型残差}
\NormalTok{v\_hat }\OtherTok{\textless{}{-}} \FunctionTok{residuals}\NormalTok{(}\FunctionTok{lm}\NormalTok{(educ }\SpecialCharTok{\textasciitilde{}}\NormalTok{ motheduc }\SpecialCharTok{+}\NormalTok{ fatheduc }\SpecialCharTok{+}\NormalTok{ exper }\SpecialCharTok{+}\NormalTok{ expersq,}
                      \AttributeTok{data =}\NormalTok{ mroz\_work))}
\CommentTok{\# Step 2: 構造方程式 + v\_hat}
\NormalTok{endog\_reg }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(lwage }\SpecialCharTok{\textasciitilde{}}\NormalTok{ educ }\SpecialCharTok{+}\NormalTok{ exper }\SpecialCharTok{+}\NormalTok{ expersq }\SpecialCharTok{+}\NormalTok{ v\_hat, }\AttributeTok{data =}\NormalTok{ mroz\_work)}
\FunctionTok{coef}\NormalTok{(}\FunctionTok{summary}\NormalTok{(endog\_reg))[}\StringTok{"v\_hat"}\NormalTok{, ]  }\CommentTok{\# t ≈ 1.67}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Estimate Std. Error    t value   Pr(>|t|) 
## 0.05816661 0.03480728 1.67110501 0.09544055
\end{verbatim}

\normalsize
\end{frame}

\begin{frame}{内生性検定の結果解釈}
\phantomsection\label{ux5185ux751fux6027ux691cux5b9aux306eux7d50ux679cux89e3ux91c8}
\begin{itemize}
\tightlist
\item
  \(\hat{\delta}_1 \approx 0.058\),
  \(t \approx 1.67\)：10\%水準で有意（示唆的）
\item
  5\%水準では帰無仮説（\(educ\)が外生）を棄却できない
\item
  \textbf{実務上の推奨}: 2SLSとOLSの両方を報告し、差異を議論
\end{itemize}
\end{frame}

\begin{frame}{15-5b 過剰識別制約の検定}
\phantomsection\label{b-ux904eux5270ux8b58ux5225ux5236ux7d04ux306eux691cux5b9a}
\begin{itemize}
\tightlist
\item
  過剰識別（除外IV数 \textgreater{} 内生変数数）の場合:
  少なくとも一部のIVが外生かを検定可能
\item
  \textbf{Sargan検定}手順:
\end{itemize}

\begin{enumerate}
[(i)]
\item
  2SLS推定を行い残差 \(\hat{u}_1\) を得る
\item
  \(\hat{u}_1\) を全外生変数に回帰し \(R^2\) を取得
\item
  検定統計量 \(nR^2 \sim \chi^2_q\)（\(q\) = 過剰識別制約数）
\end{enumerate}
\end{frame}

\begin{frame}[fragile]{Sargan検定（Rコード）}
\phantomsection\label{sarganux691cux5b9arux30b3ux30fcux30c9}
\scriptsize

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 2SLSの残差}
\NormalTok{u\_hat155 }\OtherTok{\textless{}{-}} \FunctionTok{residuals}\NormalTok{(res\_2sls155)}
\CommentTok{\# 2SLSの残差を全外生変数に回帰}
\NormalTok{oir\_reg }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(u\_hat155 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ motheduc }\SpecialCharTok{+}\NormalTok{ fatheduc }\SpecialCharTok{+}\NormalTok{ exper }\SpecialCharTok{+}\NormalTok{ expersq,}
              \AttributeTok{data =}\NormalTok{ mroz\_work)}
\NormalTok{n  }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(mroz\_work)}
\CommentTok{\# Sargan検定統計量}
\NormalTok{nR2 }\OtherTok{\textless{}{-}}\NormalTok{ n }\SpecialCharTok{*} \FunctionTok{summary}\NormalTok{(oir\_reg)}\SpecialCharTok{$}\NormalTok{r.squared}
\FunctionTok{cat}\NormalTok{(}\StringTok{"nR² ="}\NormalTok{, }\FunctionTok{round}\NormalTok{(nR2, }\DecValTok{4}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## nR² = 0.3781
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"p値 ="}\NormalTok{, }\FunctionTok{round}\NormalTok{(}\FunctionTok{pchisq}\NormalTok{(nR2, }\AttributeTok{df =} \DecValTok{1}\NormalTok{, }\AttributeTok{lower.tail =} \ConstantTok{FALSE}\NormalTok{), }\DecValTok{4}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## p値 = 0.5386
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# q = 2（IV数）{-} 1（内生変数数）= 1}
\end{Highlighting}
\end{Shaded}

\normalsize
\end{frame}

\begin{frame}{過剰識別検定の解釈}
\phantomsection\label{ux904eux5270ux8b58ux5225ux691cux5b9aux306eux89e3ux91c8}
\begin{itemize}
\tightlist
\item
  \(nR^2 \approx 0.385\), \(p \approx 0.535\) \(\Rightarrow\)
  帰無仮説（両IVが外生）を棄却できない
\item
  \(huseduc\)（夫の教育）を追加すると \(nR^2 \approx 1.11\),
  \(p \approx 0.574\)（2自由度）
\item
  \textbf{注意}:
  検定は全IVが同一の方向にバイアスを持つ場合は検出できない
\end{itemize}
\end{frame}

\section{15-6
不均一分散と2SLS}\label{ux4e0dux5747ux4e00ux5206ux6563ux30682sls}

\begin{frame}[fragile]{不均一分散頑健な2SLS推定}
\phantomsection\label{ux4e0dux5747ux4e00ux5206ux6563ux9811ux5065ux306a2slsux63a8ux5b9a}
\begin{itemize}
\tightlist
\item
  2SLSでも不均一分散が問題になりうる
\item
  OLSと同様に、\textbf{不均一分散頑健標準誤差}が利用可能
\item
  Breusch-Pagan型の検定: 2SLS残差 \(\hat{u}_1\)
  を全外生変数に回帰した際の結合有意性
\end{itemize}

\scriptsize

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 不均一分散頑健標準誤差付き2SLS}
\NormalTok{res\_hc }\OtherTok{\textless{}{-}} \FunctionTok{ivreg}\NormalTok{(lwage }\SpecialCharTok{\textasciitilde{}}\NormalTok{ educ }\SpecialCharTok{+}\NormalTok{ exper }\SpecialCharTok{+}\NormalTok{ expersq }\SpecialCharTok{|}
\NormalTok{                  motheduc }\SpecialCharTok{+}\NormalTok{ fatheduc }\SpecialCharTok{+}\NormalTok{ exper }\SpecialCharTok{+}\NormalTok{ expersq,}
                \AttributeTok{data =}\NormalTok{ mroz\_work)}
\CommentTok{\# 頑健標準誤差}
\FunctionTok{coeftest}\NormalTok{(res\_hc, }\AttributeTok{vcov =} \FunctionTok{vcovHC}\NormalTok{(res\_hc, }\AttributeTok{type =} \StringTok{"HC1"}\NormalTok{))[}\StringTok{"educ"}\NormalTok{, ]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Estimate Std. Error    t value   Pr(>|t|) 
## 0.06139663 0.03333859 1.84160854 0.06623070
\end{verbatim}

\normalsize
\end{frame}

\section{15-7/15-8
時系列・パネルデータへの応用}\label{ux6642ux7cfbux5217ux30d1ux30cdux30ebux30c7ux30fcux30bfux3078ux306eux5fdcux7528}

\begin{frame}{時系列データへの2SLS適用}
\phantomsection\label{ux6642ux7cfbux5217ux30c7ux30fcux30bfux3078ux306e2slsux9069ux7528}
\begin{itemize}
\tightlist
\item
  時系列構造方程式 {[}15.52{]}:
  \[y_t = \beta_0 + \beta_1 x_{t1} + \cdots + \beta_k x_{tk} + u_t\]
\item
  2SLSの漸近的性質は弱従属系列で成立
\item
  \textbf{注意点}:

  \begin{itemize}
  \tightlist
  \item
    トレンドや季節性がある場合は時系列ダミーを含める
  \item
    トレンド変数は常に自分自身のIVになる
  \item
    単位根を持つ変数は1階差分後に適用
  \end{itemize}
\item
  AR(1)誤差の検定: \(\hat{u}_t\) を \(\hat{u}_{t-1}\)
  に2SLSで回帰（{[}15.55{]}）
\end{itemize}
\end{frame}

\begin{frame}[fragile]{例15.10: 職業訓練と労働者生産性 (JTRAIN) --- FD +
IV}
\phantomsection\label{ux4f8b15.10-ux8077ux696dux8a13ux7df4ux3068ux52b4ux50cdux8005ux751fux7523ux6027-jtrain-fd-iv}
\begin{itemize}
\tightlist
\item
  FDモデル {[}15.57{]}:
  \[\Delta\log(scrap_i) = \delta_0 + \beta_1 \Delta hrsemp_i + \Delta u_i\]
\item
  \(\Delta hrsemp_i\) が \(\Delta u_i\) と相関する懸念 \(\Rightarrow\)
  \(\Delta grant_i\) を IV に使用
\end{itemize}

\scriptsize

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(jtrain)}
\CommentTok{\# year==1988 の行に1階差分変数(clscrap, chrsemp, cgrant)が格納されている}
\NormalTok{j88 }\OtherTok{\textless{}{-}} \FunctionTok{subset}\NormalTok{(jtrain, year }\SpecialCharTok{==} \DecValTok{1988}\NormalTok{)}
\NormalTok{j88\_clean }\OtherTok{\textless{}{-}} \FunctionTok{na.omit}\NormalTok{(j88[, }\FunctionTok{c}\NormalTok{(}\StringTok{"clscrap"}\NormalTok{, }\StringTok{"chrsemp"}\NormalTok{, }\StringTok{"cgrant"}\NormalTok{)])  }\CommentTok{\# n = 45}
\CommentTok{\# 2SLS: cgrant を chrsemp の IV として使用}
\NormalTok{res\_2sls1510 }\OtherTok{\textless{}{-}} \FunctionTok{ivreg}\NormalTok{(clscrap }\SpecialCharTok{\textasciitilde{}}\NormalTok{ chrsemp }\SpecialCharTok{|}\NormalTok{ cgrant, }\AttributeTok{data =}\NormalTok{ j88\_clean)}
\FunctionTok{coef}\NormalTok{(}\FunctionTok{summary}\NormalTok{(res\_2sls1510))[}\StringTok{"chrsemp"}\NormalTok{, ]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     Estimate   Std. Error      t value     Pr(>|t|) 
## -0.014153164  0.007914742 -1.788202786  0.080790975
\end{verbatim}

\normalsize
\end{frame}

\begin{frame}{例15.10: 結果の解釈}
\phantomsection\label{ux4f8b15.10-ux7d50ux679cux306eux89e3ux91c8}
\begin{itemize}
\tightlist
\item
  2SLS: \(\hat{\beta}_1 \approx -0.014\)（se = 0.008）:
  10時間の訓練増加で不良品率約14\%低下
\item
  OLS: \(\hat{\beta}_1 \approx -0.007\)（se = 0.005）: 2SLSはOLSの約2倍
\item
  第1段階: \(\Delta grant\) の \(t \approx 3.13\)（強い関連性）
\end{itemize}
\end{frame}

\begin{frame}{結合横断面・パネルデータへの2SLS}
\phantomsection\label{ux7d50ux5408ux6a2aux65adux9762ux30d1ux30cdux30ebux30c7ux30fcux30bfux3078ux306e2sls}
\begin{itemize}
\tightlist
\item
  結合横断面: 年ダミーは外生 \(\Rightarrow\) 通常のIVと同様に適用
\item
  \textbf{例15.9}: 出生率方程式（FERTIL1）で \(educ\)
  を内生と仮定、両親教育をIVに
\item
  パネルデータ + IV: FD後に内生性が残る場合

  \begin{itemize}
  \tightlist
  \item
    FD後のモデルで追加のIVを使用（例15.10が典型例）
  \item
    ラグ従属変数を含む動的モデルでもIV/GMM法が必要
  \end{itemize}
\end{itemize}
\end{frame}

\section{まとめ}\label{ux307eux3068ux3081}

\begin{frame}[fragile]{第15章のまとめ}
\phantomsection\label{ux7b2c15ux7ae0ux306eux307eux3068ux3081}
\footnotesize

\begin{longtable}[]{@{}lll@{}}
\toprule\noalign{}
手法 & 状況 & R関数 \\
\midrule\noalign{}
\endhead
IV (1変数) & 内生変数1個、IV1個 &
\texttt{ivreg(y\ \textasciitilde{}\ x\ \textbackslash{}\textbar{}\ z)} \\
2SLS & 内生変数1個、IV複数 &
\texttt{ivreg(y\ \textasciitilde{}\ x+w\ \textbackslash{}\textbar{}\ z+w)} \\
2SLS（複数内生） & 内生変数複数 & \texttt{ivreg()} \\
頑健SE付き2SLS & 不均一分散 & \texttt{coeftest(,\ vcovHC())} \\
\bottomrule\noalign{}
\end{longtable}

\normalsize
\end{frame}

\begin{frame}{まとめ（続き）}
\phantomsection\label{ux307eux3068ux3081ux7d9aux304d}
\begin{itemize}
\tightlist
\item
  \textbf{操作変数の2条件}:
  外生性（理論で正当化）、関連性（第1段階で検定）
\item
  \textbf{弱操作変数}: 第1段階の \(F > 10\)（Stock-Yogo ルール）
\item
  \textbf{次数条件}: 除外IV数 \(\geq\)
  内生変数数（識別のための必要条件）
\item
  \textbf{内生性検定}: 第1段階残差を構造方程式に追加して \(t\) 検定
\item
  \textbf{過剰識別検定}: \(nR^2 \sim \chi^2_q\)（\(q\) =
  過剰識別制約数）
\item
  \textbf{代償}: IVの分散はOLSより常に大きい \(\Rightarrow\)
  大標本が重要
\item
  \textbf{応用}:
  省略変数、測定誤差、時系列・パネルデータすべてに使用可能
\end{itemize}
\end{frame}

\end{document}
