% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
  ignorenonframetext,
]{beamer}
\usepackage{pgfpages}
\setbeamertemplate{caption}[numbered]
\setbeamertemplate{caption label separator}{: }
\setbeamercolor{caption name}{fg=normal text.fg}
\beamertemplatenavigationsymbolsempty
% Prevent slide breaks in the middle of a paragraph
\widowpenalties 1 10000
\raggedbottom
\setbeamertemplate{part page}{
  \centering
  \begin{beamercolorbox}[sep=16pt,center]{part title}
    \usebeamerfont{part title}\insertpart\par
  \end{beamercolorbox}
}
\setbeamertemplate{section page}{
  \centering
  \begin{beamercolorbox}[sep=12pt,center]{part title}
    \usebeamerfont{section title}\insertsection\par
  \end{beamercolorbox}
}
\setbeamertemplate{subsection page}{
  \centering
  \begin{beamercolorbox}[sep=8pt,center]{part title}
    \usebeamerfont{subsection title}\insertsubsection\par
  \end{beamercolorbox}
}
\AtBeginPart{
  \frame{\partpage}
}
\AtBeginSection{
  \ifbibliography
  \else
    \frame{\sectionpage}
  \fi
}
\AtBeginSubsection{
  \frame{\subsectionpage}
}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usetheme[]{Montpellier}
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\newif\ifbibliography
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
\usepackage{caption}
% Make caption package work with longtable
\makeatletter
\def\fnum@table{\tablename~\thetable}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
%\documentclass[unicode,10pt]{beamer}% 'unicode'が必要
\usepackage{luatexja}% 日本語を使う場合は必須
%\usepackage[japanese]{babel}	
%\usefonttheme[onlymath]{serif}
%\usepackage[T1]{fontenc} %これを使うと、ギリシャ文字が出ない
%\usepackage{textcomp}
%\usepackage[scale=1.0]{tgheros} % Sans serif font
%\usepackage[scaled]{beramono} % Monospace font
%\usepackage{luatexja-otf}
%\renewcommand{\kanjifamilydefault}{\gtdefault}
%\usepackage[haranoaji]{luatexja-preset}

% スライド番号の表示 %%%%%%%%%%%%%%%%%%%
\makeatletter
\setbeamertemplate{footline}{%
  \leavevmode%
  \hbox{%
  \begin{beamercolorbox}[wd=.5\paperwidth,ht=2.25ex,dp=1ex,right]{date in head/foot}%
    \insertframenumber{} \hspace*{2ex} % new version without total frames
  \end{beamercolorbox}}%
  \vskip0pt%
}
\makeatother
% スライド番号の表示 %%%%%%%%%%%%%%%%%%%
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{第17章: 制限従属変数モデルと標本選択修正}
\subtitle{Jeffrey Wooldridge (2016).\\
Introductory Econometrics: A Modern Approach\\
Seventh Edition. Cengage Learning.}
\author{}
\date{\vspace{-2.5em}2026-03-06}

\begin{document}
\frame{\titlepage}

\hypertarget{ux6e96ux5099}{%
\section{準備}\label{ux6e96ux5099}}

\begin{frame}[fragile]{必要なパッケージの読み込み}
\protect\hypertarget{ux5fc5ux8981ux306aux30d1ux30c3ux30b1ux30fcux30b8ux306eux8aadux307fux8fbcux307f}{}
\begin{itemize}
\tightlist
\item
  \texttt{wooldridge}: データセット
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(wooldridge)}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  \texttt{AER}: Tobitモデル推定 \texttt{tobit()}
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{install.packages}\NormalTok{(}\StringTok{"AER"}\NormalTok{)}
\FunctionTok{library}\NormalTok{(AER)}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  \texttt{survival}: 打ち切り回帰 \texttt{survreg()}
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{install.packages}\NormalTok{(}\StringTok{"survival"}\NormalTok{)}
\FunctionTok{library}\NormalTok{(survival)}
\end{Highlighting}
\end{Shaded}
\end{frame}

\hypertarget{ux4e8cux5024ux5fdcux7b54ux306eux30edux30b8ux30c3ux30c8ux3068ux30d7ux30edux30d3ux30c3ux30c8ux30e2ux30c7ux30eb}{%
\section{17-1
二値応答のロジットとプロビット・モデル}\label{ux4e8cux5024ux5fdcux7b54ux306eux30edux30b8ux30c3ux30c8ux3068ux30d7ux30edux30d3ux30c3ux30c8ux30e2ux30c7ux30eb}}

\begin{frame}{線形確率モデル (LPM) の限界}
\protect\hypertarget{ux7ddaux5f62ux78baux7387ux30e2ux30c7ux30eb-lpm-ux306eux9650ux754c}{}
\begin{itemize}
\tightlist
\item
  第7章で学んだ LPM: 二値従属変数への重回帰の適用
\item
  \textbf{問題点}:

  \begin{enumerate}
  \tightlist
  \item
    推定確率が 0 未満・1 超になりうる
  \item
    説明変数の偏効果が一定（非線形性を無視）
  \end{enumerate}
\item
  解決策: \textbf{二値応答モデル (binary response models)}
\end{itemize}

応答確率 {[}17.1, 17.2{]}:
\[P(y = 1|\mathbf{x}) = G(\beta_0 + \beta_1 x_1 + \cdots + \beta_k x_k) = G(\beta_0 + \mathbf{x\beta})\]
\end{frame}

\begin{frame}{17-1a ロジットとプロビット・モデルの定式化}
\protect\hypertarget{a-ux30edux30b8ux30c3ux30c8ux3068ux30d7ux30edux30d3ux30c3ux30c8ux30e2ux30c7ux30ebux306eux5b9aux5f0fux5316}{}
\(G\) は \((0,1)\) の値をとる関数:

\textbf{ロジット・モデル} {[}17.3{]}:
\[G(z) = \frac{\exp(z)}{1 + \exp(z)} = \Lambda(z)\]
（標準ロジスティック分布のCDF）

\textbf{プロビット・モデル} {[}17.4{]}:
\[G(z) = \Phi(z) = \int_{-\infty}^{z} \phi(v)\,dv\]
（標準正規分布のCDF）
\end{frame}

\begin{frame}{潜在変数モデルによる導出}
\protect\hypertarget{ux6f5cux5728ux5909ux6570ux30e2ux30c7ux30ebux306bux3088ux308bux5c0eux51fa}{}
\textbf{潜在変数モデル} {[}17.6{]}:
\[y^* = \beta_0 + \mathbf{x\beta} + e, \quad y = \mathbf{1}[y^* > 0]\]

\begin{itemize}
\tightlist
\item
  \(e\) がロジスティック分布 \(\Rightarrow\) \textbf{ロジット}
\item
  \(e\) が標準正規分布 \(\Rightarrow\)
  \textbf{プロビット}（計量経済学で主流）
\item
  \(\beta_j\) の大きさ自体は通常解釈困難（\(y^*\) の単位が不明）
\item
  ただし符号と統計的有意性は解釈可能
\end{itemize}
\end{frame}

\begin{frame}{偏効果}
\protect\hypertarget{ux504fux52b9ux679c}{}
連続変数 \(x_j\) の応答確率への偏効果 {[}17.7{]}:
\[\frac{\partial p(\mathbf{x})}{\partial x_j} = g(\beta_0 + \mathbf{x\beta})\beta_j, \quad g(z) \equiv \frac{dG}{dz}(z)\]

\begin{itemize}
\tightlist
\item
  \(g(z) > 0\) なので偏効果の\textbf{符号}は \(\beta_j\) の符号と同じ
\item
  効果の\textbf{大きさ}は全変数の値に依存
\end{itemize}

二値変数 \(x_1\) の効果 {[}17.8{]}:
\[G(\beta_0 + \beta_1 + \beta_2 x_2 + \cdots + \beta_k x_k) - G(\beta_0 + \beta_2 x_2 + \cdots + \beta_k x_k)\]
\end{frame}

\begin{frame}{17-1b ロジット・プロビットの最尤推定}
\protect\hypertarget{b-ux30edux30b8ux30c3ux30c8ux30d7ux30edux30d3ux30c3ux30c8ux306eux6700ux5c24ux63a8ux5b9a}{}
\begin{itemize}
\tightlist
\item
  LPMはOLS推定可能だが、ロジット・プロビットはOLS不可
\item
  \textbf{最尤推定法 (MLE)} を使用
\end{itemize}

対数尤度関数 {[}17.11{]}:
\[\ell_i(\boldsymbol{\beta}) = y_i \log[G(\mathbf{x}_i\boldsymbol{\beta})] + (1-y_i)\log[1-G(\mathbf{x}_i\boldsymbol{\beta})]\]

\(\mathcal{L}(\boldsymbol{\beta}) = \sum_{i=1}^n \ell_i(\boldsymbol{\beta})\)
を最大化 \(\Rightarrow\) MLE は一致・漸近正規・漸近効率
\end{frame}

\begin{frame}{17-1c 複数の仮説の検定}
\protect\hypertarget{c-ux8907ux6570ux306eux4eeeux8aacux306eux691cux5b9a}{}
\textbf{尤度比 (LR) 統計量} {[}17.12{]}:
\[LR = 2(\mathcal{L}_{ur} - \mathcal{L}_r) \overset{a}{\sim} \chi^2_q\]

\begin{itemize}
\tightlist
\item
  \(q\): 制約数
\item
  \(\mathcal{L}_{ur}\): 非制約モデルの対数尤度
\item
  \(\mathcal{L}_r\): 制約モデルの対数尤度（対数尤度は常に負なので
  \(LR \geq 0\)）
\end{itemize}

\textbf{Wald統計量}: 線形モデルの \(F\)
統計量に相当（計量ソフトが自動計算）
\end{frame}

\begin{frame}{17-1d 推定値の解釈: スケール因子}
\protect\hypertarget{d-ux63a8ux5b9aux5024ux306eux89e3ux91c8-ux30b9ux30b1ux30fcux30ebux56e0ux5b50}{}
ロジット・プロビット係数の大きさは直接解釈困難 →
\textbf{スケール因子}で調整

\textbf{平均における偏効果 (PEA)} {[}17.14{]}:
\[g(\hat{\beta}_0 + \bar{\mathbf{x}}\hat{\boldsymbol{\beta}}) = g\!\left(\hat{\beta}_0 + \hat{\beta}_1\bar{x}_1 + \cdots + \hat{\beta}_k\bar{x}_k\right)\]

\textbf{平均偏効果 (APE) / 平均限界効果 (AME)} {[}17.15{]}:
\[n^{-1}\sum_{i=1}^n g(\hat{\beta}_0 + \mathbf{x}_i\hat{\boldsymbol{\beta}})\]

\begin{itemize}
\tightlist
\item
  APEは離散変数の平均の問題を回避するためより推奨
\end{itemize}
\end{frame}

\begin{frame}{適合度指標}
\protect\hypertarget{ux9069ux5408ux5ea6ux6307ux6a19}{}
\textbf{正確な予測割合 (percent correctly predicted)}: -
\(\hat{y}_i = 1\) if \(\hat{p}_i \geq 0.5\)、\(\hat{y}_i = 0\) if
\(\hat{p}_i < 0.5\) - \(\hat{y}_i = y_i\) となる割合

\textbf{疑似 \(R^2\) (McFadden)}: \[1 - \mathcal{L}_{ur}/\mathcal{L}_o\]
- \(\mathcal{L}_o\): 定数項のみのモデルの対数尤度 - \(0.2 \sim 0.4\)
で「優れた適合」とされる目安
\end{frame}

\hypertarget{d-ux4f8b17.1-ux65e2ux5a5aux5973ux6027ux306eux52b4ux50cdux53c2ux52a0}{%
\section{17-1d 例17.1:
既婚女性の労働参加}\label{d-ux4f8b17.1-ux65e2ux5a5aux5973ux6027ux306eux52b4ux50cdux53c2ux52a0}}

\begin{frame}[fragile]{例17.1: LPM・ロジット・プロビットの比較 (MROZ)}
\protect\hypertarget{ux4f8b17.1-lpmux30edux30b8ux30c3ux30c8ux30d7ux30edux30d3ux30c3ux30c8ux306eux6bd4ux8f03-mroz}{}
\begin{itemize}
\tightlist
\item
  データ: 既婚女性 753 人、被説明変数 \texttt{inlf}（就業参加ダミー）
\item
  表 17.1 の再現
\end{itemize}

\footnotesize

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(mroz)}
\CommentTok{\# LPM (OLS)}
\NormalTok{res\_lpm }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(inlf }\SpecialCharTok{\textasciitilde{}}\NormalTok{ nwifeinc }\SpecialCharTok{+}\NormalTok{ educ }\SpecialCharTok{+}\NormalTok{ exper }\SpecialCharTok{+}\NormalTok{ expersq }\SpecialCharTok{+}
\NormalTok{                age }\SpecialCharTok{+}\NormalTok{ kidslt6 }\SpecialCharTok{+}\NormalTok{ kidsge6, }\AttributeTok{data =}\NormalTok{ mroz)}
\CommentTok{\# ロジット}
\NormalTok{res\_logit }\OtherTok{\textless{}{-}} \FunctionTok{glm}\NormalTok{(inlf }\SpecialCharTok{\textasciitilde{}}\NormalTok{ nwifeinc }\SpecialCharTok{+}\NormalTok{ educ }\SpecialCharTok{+}\NormalTok{ exper }\SpecialCharTok{+}\NormalTok{ expersq }\SpecialCharTok{+}
\NormalTok{                   age }\SpecialCharTok{+}\NormalTok{ kidslt6 }\SpecialCharTok{+}\NormalTok{ kidsge6,}
                 \AttributeTok{data =}\NormalTok{ mroz, }\AttributeTok{family =} \FunctionTok{binomial}\NormalTok{(}\AttributeTok{link =} \StringTok{"logit"}\NormalTok{))}
\CommentTok{\# プロビット}
\NormalTok{res\_probit }\OtherTok{\textless{}{-}} \FunctionTok{glm}\NormalTok{(inlf }\SpecialCharTok{\textasciitilde{}}\NormalTok{ nwifeinc }\SpecialCharTok{+}\NormalTok{ educ }\SpecialCharTok{+}\NormalTok{ exper }\SpecialCharTok{+}\NormalTok{ expersq }\SpecialCharTok{+}
\NormalTok{                    age }\SpecialCharTok{+}\NormalTok{ kidslt6 }\SpecialCharTok{+}\NormalTok{ kidsge6,}
                  \AttributeTok{data =}\NormalTok{ mroz, }\AttributeTok{family =} \FunctionTok{binomial}\NormalTok{(}\AttributeTok{link =} \StringTok{"probit"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\normalsize
\end{frame}

\begin{frame}[fragile]{例17.1: 係数の比較（表17.1）}
\protect\hypertarget{ux4f8b17.1-ux4fc2ux6570ux306eux6bd4ux8f03ux886817.1}{}
\footnotesize

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{round}\NormalTok{(}\FunctionTok{cbind}\NormalTok{(}
  \AttributeTok{LPM    =} \FunctionTok{coef}\NormalTok{(res\_lpm),}
  \AttributeTok{Logit  =} \FunctionTok{coef}\NormalTok{(res\_logit),}
  \AttributeTok{Probit =} \FunctionTok{coef}\NormalTok{(res\_probit)}
\NormalTok{), }\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                LPM  Logit Probit
## (Intercept)  0.586  0.425  0.270
## nwifeinc    -0.003 -0.021 -0.012
## educ         0.038  0.221  0.131
## exper        0.039  0.206  0.123
## expersq     -0.001 -0.003 -0.002
## age         -0.016 -0.088 -0.053
## kidslt6     -0.262 -1.443 -0.868
## kidsge6      0.013  0.060  0.036
\end{verbatim}

\normalsize
\end{frame}

\begin{frame}[fragile]{例17.1: 正確な予測割合}
\protect\hypertarget{ux4f8b17.1-ux6b63ux78baux306aux4e88ux6e2cux5272ux5408}{}
\footnotesize

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pred\_lpm    }\OtherTok{\textless{}{-}} \FunctionTok{as.numeric}\NormalTok{(}\FunctionTok{fitted}\NormalTok{(res\_lpm)    }\SpecialCharTok{\textgreater{}=} \FloatTok{0.5}\NormalTok{)}
\NormalTok{pred\_logit  }\OtherTok{\textless{}{-}} \FunctionTok{as.numeric}\NormalTok{(}\FunctionTok{fitted}\NormalTok{(res\_logit)  }\SpecialCharTok{\textgreater{}=} \FloatTok{0.5}\NormalTok{)}
\NormalTok{pred\_probit }\OtherTok{\textless{}{-}} \FunctionTok{as.numeric}\NormalTok{(}\FunctionTok{fitted}\NormalTok{(res\_probit) }\SpecialCharTok{\textgreater{}=} \FloatTok{0.5}\NormalTok{)}
\FunctionTok{cat}\NormalTok{(}\StringTok{"正確な予測割合 (\%):}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 正確な予測割合 (%):
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"  LPM:   "}\NormalTok{, }\FunctionTok{round}\NormalTok{(}\DecValTok{100} \SpecialCharTok{*} \FunctionTok{mean}\NormalTok{(pred\_lpm    }\SpecialCharTok{==}\NormalTok{ mroz}\SpecialCharTok{$}\NormalTok{inlf), }\DecValTok{1}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   LPM:    73.4
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"  Logit: "}\NormalTok{, }\FunctionTok{round}\NormalTok{(}\DecValTok{100} \SpecialCharTok{*} \FunctionTok{mean}\NormalTok{(pred\_logit  }\SpecialCharTok{==}\NormalTok{ mroz}\SpecialCharTok{$}\NormalTok{inlf), }\DecValTok{1}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Logit:  73.6
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"  Probit:"}\NormalTok{, }\FunctionTok{round}\NormalTok{(}\DecValTok{100} \SpecialCharTok{*} \FunctionTok{mean}\NormalTok{(pred\_probit }\SpecialCharTok{==}\NormalTok{ mroz}\SpecialCharTok{$}\NormalTok{inlf), }\DecValTok{1}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Probit: 73.4
\end{verbatim}

\normalsize

\begin{itemize}
\tightlist
\item
  LPM・ロジット・プロビットで正確な予測割合はほぼ同じ
\end{itemize}
\end{frame}

\begin{frame}[fragile]{例17.1: 疑似 \(R^2\)（McFadden）}
\protect\hypertarget{ux4f8b17.1-ux7591ux4f3c-r2mcfadden}{}
\footnotesize

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{L0 }\OtherTok{\textless{}{-}} \FunctionTok{logLik}\NormalTok{(}\FunctionTok{glm}\NormalTok{(inlf }\SpecialCharTok{\textasciitilde{}} \DecValTok{1}\NormalTok{, }\AttributeTok{data =}\NormalTok{ mroz, }\AttributeTok{family =}\NormalTok{ binomial))}
\FunctionTok{cat}\NormalTok{(}\StringTok{"疑似R² Logit: "}\NormalTok{, }\FunctionTok{round}\NormalTok{(}\DecValTok{1} \SpecialCharTok{{-}} \FunctionTok{logLik}\NormalTok{(res\_logit) }\SpecialCharTok{/}\NormalTok{L0, }\DecValTok{3}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 疑似R² Logit:  0.22
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"疑似R² Probit:"}\NormalTok{, }\FunctionTok{round}\NormalTok{(}\DecValTok{1} \SpecialCharTok{{-}} \FunctionTok{logLik}\NormalTok{(res\_probit)}\SpecialCharTok{/}\NormalTok{L0, }\DecValTok{3}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 疑似R² Probit: 0.221
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"LPM R²:       "}\NormalTok{, }\FunctionTok{round}\NormalTok{(}\FunctionTok{summary}\NormalTok{(res\_lpm)}\SpecialCharTok{$}\NormalTok{r.squared, }\DecValTok{3}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## LPM R²:        0.264
\end{verbatim}

\normalsize

\begin{itemize}
\tightlist
\item
  ロジット・プロビットの疑似 \(R^2 \approx 0.22\)（LPM の
  \(R^2 \approx 0.26\) に近い）
\item
  3モデルとも同程度の説明力
\end{itemize}
\end{frame}

\begin{frame}[fragile]{例17.1: APEスケール因子の計算}
\protect\hypertarget{ux4f8b17.1-apeux30b9ux30b1ux30fcux30ebux56e0ux5b50ux306eux8a08ux7b97}{}
\footnotesize

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# プロビット: g(z) = φ(z)}
\NormalTok{xb\_hat }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(res\_probit, }\AttributeTok{type =} \StringTok{"link"}\NormalTok{)}
\NormalTok{ape\_scale\_probit }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(}\FunctionTok{dnorm}\NormalTok{(xb\_hat))}
\CommentTok{\# ロジット: g(z) = Λ(z)[1{-}Λ(z)]}
\NormalTok{p\_hat }\OtherTok{\textless{}{-}} \FunctionTok{fitted}\NormalTok{(res\_logit)}
\NormalTok{ape\_scale\_logit }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(p\_hat }\SpecialCharTok{*}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ p\_hat))}
\FunctionTok{cat}\NormalTok{(}\StringTok{"APEスケール因子:}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## APEスケール因子:
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"  Probit:"}\NormalTok{, }\FunctionTok{round}\NormalTok{(ape\_scale\_probit, }\DecValTok{3}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Probit: 0.301
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"  Logit: "}\NormalTok{, }\FunctionTok{round}\NormalTok{(ape\_scale\_logit,  }\DecValTok{3}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Logit:  0.179
\end{verbatim}

\normalsize
\end{frame}

\begin{frame}[fragile]{例17.1: APEのLPMとの比較（表17.2）}
\protect\hypertarget{ux4f8b17.1-apeux306elpmux3068ux306eux6bd4ux8f03ux886817.2}{}
\footnotesize

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 各変数のAPE比較（表17.2より educ, exper, kidslt6）}
\NormalTok{vars\_ape }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"educ"}\NormalTok{, }\StringTok{"exper"}\NormalTok{, }\StringTok{"kidslt6"}\NormalTok{)}
\NormalTok{ape\_tbl }\OtherTok{\textless{}{-}} \FunctionTok{cbind}\NormalTok{(}
  \AttributeTok{LPM    =} \FunctionTok{coef}\NormalTok{(res\_lpm)[vars\_ape],}
  \AttributeTok{Logit  =}\NormalTok{ ape\_scale\_logit  }\SpecialCharTok{*} \FunctionTok{coef}\NormalTok{(res\_logit)[vars\_ape],}
  \AttributeTok{Probit =}\NormalTok{ ape\_scale\_probit }\SpecialCharTok{*} \FunctionTok{coef}\NormalTok{(res\_probit)[vars\_ape]}
\NormalTok{)}
\FunctionTok{round}\NormalTok{(ape\_tbl, }\DecValTok{4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##             LPM   Logit  Probit
## educ     0.0380  0.0395  0.0394
## exper    0.0395  0.0368  0.0371
## kidslt6 -0.2618 -0.2578 -0.2612
\end{verbatim}

\normalsize

\begin{itemize}
\tightlist
\item
  APE はLPM推定値に非常に近い（3モデルで整合的）
\end{itemize}
\end{frame}

\hypertarget{ux30b3ux30fcux30caux30fcux89e3ux5fdcux7b54ux306eux305fux3081ux306etobitux30e2ux30c7ux30eb}{%
\section{17-2
コーナー解応答のためのTobitモデル}\label{ux30b3ux30fcux30caux30fcux89e3ux5fdcux7b54ux306eux305fux3081ux306etobitux30e2ux30c7ux30eb}}

\begin{frame}{コーナー解応答とは}
\protect\hypertarget{ux30b3ux30fcux30caux30fcux89e3ux5fdcux7b54ux3068ux306f}{}
\begin{itemize}
\tightlist
\item
  \textbf{制限従属変数}のもう1つの重要な型:

  \begin{itemize}
  \tightlist
  \item
    正の確率でゼロをとる（人口の相当割合がゼロを選択）
  \item
    正の値をとるときは連続的
  \item
    例: 家計の慈善寄付額、年間就業時間、年金積立額
  \end{itemize}
\item
  \textbf{コーナー解 (corner solution)}: 最適化行動の結果としてのゼロ
\item
  LPMやロジット・プロビットとは異なる問題設定
\end{itemize}
\end{frame}

\begin{frame}{Tobitモデルの定式化}
\protect\hypertarget{tobitux30e2ux30c7ux30ebux306eux5b9aux5f0fux5316}{}
潜在変数モデル {[}17.18, 17.19{]}:
\[y^* = \beta_0 + \mathbf{x\beta} + u, \quad u|\mathbf{x} \sim \text{Normal}(0, \sigma^2)\]
\[y = \max(0, y^*)\]

\(y_i = 0\) の確率 {[}17.21{]}:
\[P(y = 0|\mathbf{x}) = 1 - \Phi(\mathbf{x\beta}/\sigma)\]

対数尤度 {[}17.22{]}:
\[\ell_i = \mathbf{1}(y_i=0)\log[1-\Phi(\mathbf{x}_i\boldsymbol{\beta}/\sigma)]
         + \mathbf{1}(y_i>0)\log\!\left\{\tfrac{1}{\sigma}\phi\!\left[\tfrac{y_i - \mathbf{x}_i\boldsymbol{\beta}}{\sigma}\right]\right\}\]
\end{frame}

\begin{frame}{17-2a Tobit推定値の解釈}
\protect\hypertarget{a-tobitux63a8ux5b9aux5024ux306eux89e3ux91c8}{}
\textbf{条件付き期待値} (\(y > 0\) のとき) {[}17.24{]}:
\[E(y|y>0, \mathbf{x}) = \mathbf{x\beta} + \sigma\lambda(\mathbf{x\beta}/\sigma)\]

\textbf{逆ミルズ比}: \(\lambda(c) = \phi(c)/\Phi(c)\)（常に正）

\textbf{無条件期待値} {[}17.25{]}:
\[E(y|\mathbf{x}) = \Phi(\mathbf{x\beta}/\sigma)\mathbf{x\beta} + \sigma\phi(\mathbf{x\beta}/\sigma)\]

\(E(y|\mathbf{x})\) への偏効果 {[}17.30{]}:
\[\frac{\partial E(y|\mathbf{x})}{\partial x_j} = \beta_j\,\Phi(\mathbf{x\beta}/\sigma)\]
\end{frame}

\begin{frame}{Tobit偏効果とOLSの比較}
\protect\hypertarget{tobitux504fux52b9ux679cux3068olsux306eux6bd4ux8f03}{}
\begin{itemize}
\tightlist
\item
  OLS係数 \(\tilde{\gamma}_j\) との比較には調整が必要
\end{itemize}

\textbf{PEAスケール因子}:
\(\Phi(\bar{\mathbf{x}}\hat{\boldsymbol{\beta}}/\hat{\sigma})\) -
\(\hat{\beta}_j \times \Phi(\bar{\mathbf{x}}\hat{\boldsymbol{\beta}}/\hat{\sigma}) \approx \tilde{\gamma}_j\)

\textbf{APEスケール因子}:
\(n^{-1}\sum_{i=1}^n \Phi(\mathbf{x}_i\hat{\boldsymbol{\beta}}/\hat{\sigma})\)

コーナー解では \(\sigma\) も経済的に重要（補助的パラメータではない）
\end{frame}

\begin{frame}[fragile]{例17.2: 既婚女性の年間就業時間 (MROZ)}
\protect\hypertarget{ux4f8b17.2-ux65e2ux5a5aux5973ux6027ux306eux5e74ux9593ux5c31ux696dux6642ux9593-mroz}{}
\begin{itemize}
\tightlist
\item
  753 人中 325 人が就業時間ゼロ → Tobit が適切
\item
  正の就業時間は 12 〜 4,950 時間と広範囲
\item
  表 17.3 の再現
\end{itemize}

\footnotesize

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(mroz)}
\CommentTok{\# OLS（全観測）}
\NormalTok{res\_ols172 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(hours }\SpecialCharTok{\textasciitilde{}}\NormalTok{ nwifeinc }\SpecialCharTok{+}\NormalTok{ educ }\SpecialCharTok{+}\NormalTok{ exper }\SpecialCharTok{+}\NormalTok{ expersq }\SpecialCharTok{+}
\NormalTok{                   age }\SpecialCharTok{+}\NormalTok{ kidslt6 }\SpecialCharTok{+}\NormalTok{ kidsge6, }\AttributeTok{data =}\NormalTok{ mroz)}
\CommentTok{\# Tobit MLE（AER::tobit, 左打ち切り at 0）}
\NormalTok{res\_tobit172 }\OtherTok{\textless{}{-}} \FunctionTok{tobit}\NormalTok{(hours }\SpecialCharTok{\textasciitilde{}}\NormalTok{ nwifeinc }\SpecialCharTok{+}\NormalTok{ educ }\SpecialCharTok{+}\NormalTok{ exper }\SpecialCharTok{+}\NormalTok{ expersq }\SpecialCharTok{+}
\NormalTok{                        age }\SpecialCharTok{+}\NormalTok{ kidslt6 }\SpecialCharTok{+}\NormalTok{ kidsge6,}
                      \AttributeTok{data =}\NormalTok{ mroz, }\AttributeTok{left =} \DecValTok{0}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\normalsize
\end{frame}

\begin{frame}[fragile]{例17.2: OLS vs Tobit（表17.3）}
\protect\hypertarget{ux4f8b17.2-ols-vs-tobitux886817.3}{}
\footnotesize

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 係数とσの比較}
\NormalTok{b\_ols   }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\FunctionTok{coef}\NormalTok{(res\_ols172),   }\AttributeTok{sigma =} \FunctionTok{summary}\NormalTok{(res\_ols172)}\SpecialCharTok{$}\NormalTok{sigma)}
\NormalTok{b\_tobit }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\FunctionTok{coef}\NormalTok{(res\_tobit172)[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{8}\NormalTok{], }\AttributeTok{sigma =}\NormalTok{ res\_tobit172}\SpecialCharTok{$}\NormalTok{scale)}
\FunctionTok{round}\NormalTok{(}\FunctionTok{cbind}\NormalTok{(}\AttributeTok{OLS =}\NormalTok{ b\_ols, }\AttributeTok{Tobit =}\NormalTok{ b\_tobit), }\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                 OLS   Tobit
## (Intercept) 1330.48  965.31
## nwifeinc      -3.45   -8.81
## educ          28.76   80.65
## exper         65.67  131.56
## expersq       -0.70   -1.86
## age          -30.51  -54.41
## kidslt6     -442.09 -894.02
## kidsge6      -32.78  -16.22
## sigma        750.18 1122.02
\end{verbatim}

\normalsize
\end{frame}

\begin{frame}[fragile]{例17.2: APEスケール因子}
\protect\hypertarget{ux4f8b17.2-apeux30b9ux30b1ux30fcux30ebux56e0ux5b50}{}
\footnotesize

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{xb\_lin    }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(res\_tobit172)}
\NormalTok{sigma\_hat }\OtherTok{\textless{}{-}}\NormalTok{ res\_tobit172}\SpecialCharTok{$}\NormalTok{scale}
\NormalTok{ape\_scale\_tobit }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(}\FunctionTok{pnorm}\NormalTok{(xb\_lin }\SpecialCharTok{/}\NormalTok{ sigma\_hat))}
\FunctionTok{cat}\NormalTok{(}\StringTok{"APEスケール因子 (Tobit):"}\NormalTok{, }\FunctionTok{round}\NormalTok{(ape\_scale\_tobit, }\DecValTok{3}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## APEスケール因子 (Tobit): 0.589
\end{verbatim}

\normalsize
\end{frame}

\begin{frame}[fragile]{例17.2: 変数別APE比較（表17.4）}
\protect\hypertarget{ux4f8b17.2-ux5909ux6570ux5225apeux6bd4ux8f03ux886817.4}{}
\footnotesize

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{vars172 }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"nwifeinc"}\NormalTok{,}\StringTok{"educ"}\NormalTok{,}\StringTok{"exper"}\NormalTok{,}\StringTok{"kidslt6"}\NormalTok{,}\StringTok{"kidsge6"}\NormalTok{,}\StringTok{"age"}\NormalTok{)}
\NormalTok{ape\_tbl172 }\OtherTok{\textless{}{-}} \FunctionTok{cbind}\NormalTok{(}
  \AttributeTok{Linear    =} \FunctionTok{coef}\NormalTok{(res\_ols172)[vars172],}
  \AttributeTok{Tobit\_APE =}\NormalTok{ ape\_scale\_tobit }\SpecialCharTok{*} \FunctionTok{coef}\NormalTok{(res\_tobit172)[vars172]}
\NormalTok{)}
\FunctionTok{round}\NormalTok{(ape\_tbl172, }\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           Linear Tobit_APE
## nwifeinc   -3.45     -5.19
## educ       28.76     47.47
## exper      65.67     77.45
## kidslt6  -442.09   -526.28
## kidsge6   -32.78     -9.55
## age       -30.51    -32.03
\end{verbatim}

\normalsize

\begin{itemize}
\tightlist
\item
  Tobit APE は OLS 係数より全体的に大きい（特に \texttt{educ},
  \texttt{kidslt6}）
\end{itemize}
\end{frame}

\begin{frame}{17-2b Tobitモデルの定式化の問題}
\protect\hypertarget{b-tobitux30e2ux30c7ux30ebux306eux5b9aux5f0fux5316ux306eux554fux984c}{}
\begin{itemize}
\tightlist
\item
  Tobit は正規性・均一分散を仮定 → 違反時に MLE は不一致
\end{itemize}

\textbf{簡易チェック}: 二値変数 \(w = \mathbf{1}[y > 0]\)
をプロビット推定 - プロビット係数 \(\hat{\gamma}_j\) は Tobit 係数
\(\hat{\beta}_j/\hat{\sigma}\) に近いはず -
符号が異なる・大きさが極端に異なる → Tobit 不適

\textbf{ハードル（2部分）モデル}: - \(P(y > 0|\mathbf{x})\) と
\(E(y|y>0, \mathbf{x})\) に別々のパラメータを使用 -
コーナー解に対してより柔軟（ただし推定は複雑）
\end{frame}

\hypertarget{ux30ddux30a2ux30bdux30f3ux56deux5e30ux30e2ux30c7ux30eb}{%
\section{17-3
ポアソン回帰モデル}\label{ux30ddux30a2ux30bdux30f3ux56deux5e30ux30e2ux30c7ux30eb}}

\begin{frame}{カウント変数とポアソン回帰}
\protect\hypertarget{ux30abux30a6ux30f3ux30c8ux5909ux6570ux3068ux30ddux30a2ux30bdux30f3ux56deux5e30}{}
\begin{itemize}
\item
  \textbf{カウント変数}: 非負の整数値 \(\{0, 1, 2, \ldots\}\)
  をとる従属変数

  \begin{itemize}
  \tightlist
  \item
    例: 年間逮捕回数、年間特許申請数、子どもの数
  \end{itemize}
\item
  ゼロが多い場合、OLS は適切でない
\item
  条件付き期待値を指数関数でモデル化 {[}17.31{]}:
  \[E(y|x_1, \ldots, x_k) = \exp(\beta_0 + \beta_1 x_1 + \cdots + \beta_k x_k)\]
\end{itemize}

両辺の対数 {[}17.32{]}:
\[\log[E(y|\mathbf{x})] = \beta_0 + \beta_1 x_1 + \cdots + \beta_k x_k\]

\(x_j\) が1単位増加 → \(E(y|\mathbf{x})\) が約 \(100\beta_j\%\) 変化
\end{frame}

\begin{frame}{ポアソン回帰の推定}
\protect\hypertarget{ux30ddux30a2ux30bdux30f3ux56deux5e30ux306eux63a8ux5b9a}{}
\textbf{ポアソン分布}:
\(P(y = h|\mathbf{x}) = \exp[-\exp(\mathbf{x\beta})][\exp(\mathbf{x\beta})]^h/h!\)

\textbf{ポアソン対数尤度} {[}17.33{]}:
\[\mathcal{L}(\boldsymbol{\beta}) = \sum_{i=1}^n \{y_i \mathbf{x}_i\boldsymbol{\beta} - \exp(\mathbf{x}_i\boldsymbol{\beta})\}\]

ポアソン分布の等分散制約 {[}17.34{]}:
\[\text{Var}(y|\mathbf{x}) = E(y|\mathbf{x})\]

\begin{itemize}
\tightlist
\item
  制約が成り立たなくても \textbf{QMLE} として \(\beta_j\) は一致推定
\item
  \textbf{過分散} (\(\text{Var} > E\)) の場合 → 修正標準誤差を使用
\end{itemize}
\end{frame}

\begin{frame}{過分散の対処}
\protect\hypertarget{ux904eux5206ux6563ux306eux5bfeux51e6}{}
分散が平均に比例する仮定 {[}17.35{]}:
\[\text{Var}(y|\mathbf{x}) = \sigma^2 E(y|\mathbf{x})\]

\(\sigma^2 > 1\): 過分散、\(\sigma^2 < 1\): 過少分散

一致推定量 {[}テキスト p.581{]}:
\[\hat{\sigma}^2 = \frac{1}{n-k-1}\sum_{i=1}^n \frac{\hat{u}_i^2}{\hat{y}_i}\]

\begin{itemize}
\tightlist
\item
  \(\hat{\sigma} > 1\) なら通常のポアソン標準誤差に \(\hat{\sigma}\)
  を掛けて修正
\end{itemize}
\end{frame}

\begin{frame}[fragile]{例17.3: 若い男性の逮捕回数 (CRIME1)}
\protect\hypertarget{ux4f8b17.3-ux82e5ux3044ux7537ux6027ux306eux902eux6355ux56deux6570-crime1}{}
\begin{itemize}
\tightlist
\item
  データ: 2,725 人、被説明変数 \texttt{narr86}（1986年逮捕回数）
\item
  1,970 人が逮捕ゼロ（0が72.3\%）→ ポアソン回帰が適切
\item
  表 17.5 の再現
\end{itemize}

\footnotesize

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(crime1)}
\CommentTok{\# OLS}
\NormalTok{res\_ols173 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(narr86 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ pcnv }\SpecialCharTok{+}\NormalTok{ avgsen }\SpecialCharTok{+}\NormalTok{ tottime }\SpecialCharTok{+}\NormalTok{ ptime86 }\SpecialCharTok{+}
\NormalTok{                   qemp86 }\SpecialCharTok{+}\NormalTok{ inc86 }\SpecialCharTok{+}\NormalTok{ black }\SpecialCharTok{+}\NormalTok{ hispan }\SpecialCharTok{+}\NormalTok{ born60,}
                 \AttributeTok{data =}\NormalTok{ crime1)}
\CommentTok{\# ポアソン QMLE}
\NormalTok{res\_poisson }\OtherTok{\textless{}{-}} \FunctionTok{glm}\NormalTok{(narr86 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ pcnv }\SpecialCharTok{+}\NormalTok{ avgsen }\SpecialCharTok{+}\NormalTok{ tottime }\SpecialCharTok{+}\NormalTok{ ptime86 }\SpecialCharTok{+}
\NormalTok{                     qemp86 }\SpecialCharTok{+}\NormalTok{ inc86 }\SpecialCharTok{+}\NormalTok{ black }\SpecialCharTok{+}\NormalTok{ hispan }\SpecialCharTok{+}\NormalTok{ born60,}
                   \AttributeTok{data =}\NormalTok{ crime1, }\AttributeTok{family =}\NormalTok{ poisson)}
\end{Highlighting}
\end{Shaded}

\normalsize
\end{frame}

\begin{frame}[fragile]{例17.3: 過分散パラメータの推定}
\protect\hypertarget{ux4f8b17.3-ux904eux5206ux6563ux30d1ux30e9ux30e1ux30fcux30bfux306eux63a8ux5b9a}{}
\footnotesize

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n   }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(crime1)}
\NormalTok{k1  }\OtherTok{\textless{}{-}} \FunctionTok{length}\NormalTok{(}\FunctionTok{coef}\NormalTok{(res\_poisson))}
\NormalTok{u\_hat }\OtherTok{\textless{}{-}} \FunctionTok{residuals}\NormalTok{(res\_poisson, }\AttributeTok{type =} \StringTok{"response"}\NormalTok{)}
\NormalTok{y\_hat }\OtherTok{\textless{}{-}} \FunctionTok{fitted}\NormalTok{(res\_poisson)}
\NormalTok{sigma2\_hat }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(u\_hat}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{/}\NormalTok{ y\_hat) }\SpecialCharTok{/}\NormalTok{ (n }\SpecialCharTok{{-}}\NormalTok{ k1)}
\FunctionTok{cat}\NormalTok{(}\StringTok{"過分散パラメータ σ̂² ="}\NormalTok{, }\FunctionTok{round}\NormalTok{(sigma2\_hat, }\DecValTok{3}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 過分散パラメータ σ̂² = 1.517
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"QMLE標準誤差の修正倍率 σ̂ ="}\NormalTok{, }\FunctionTok{round}\NormalTok{(}\FunctionTok{sqrt}\NormalTok{(sigma2\_hat), }\DecValTok{3}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## QMLE標準誤差の修正倍率 σ̂ = 1.232
\end{verbatim}

\normalsize

\begin{itemize}
\tightlist
\item
  \(\hat{\sigma} = 1.232 > 1\) → 過分散が存在 → 通常の MLE 標準誤差を
  \(\hat{\sigma}\) 倍に修正
\end{itemize}
\end{frame}

\begin{frame}[fragile]{例17.3: OLS vs ポアソン回帰（表17.5）}
\protect\hypertarget{ux4f8b17.3-ols-vs-ux30ddux30a2ux30bdux30f3ux56deux5e30ux886817.5}{}
\scriptsize

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{vars173 }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"pcnv"}\NormalTok{,}\StringTok{"avgsen"}\NormalTok{,}\StringTok{"tottime"}\NormalTok{,}\StringTok{"ptime86"}\NormalTok{,}\StringTok{"qemp86"}\NormalTok{,}
             \StringTok{"inc86"}\NormalTok{,}\StringTok{"black"}\NormalTok{,}\StringTok{"hispan"}\NormalTok{,}\StringTok{"born60"}\NormalTok{)}
\FunctionTok{round}\NormalTok{(}\FunctionTok{cbind}\NormalTok{(}
  \AttributeTok{OLS     =} \FunctionTok{coef}\NormalTok{(res\_ols173)[vars173],}
  \AttributeTok{Poisson =} \FunctionTok{coef}\NormalTok{(res\_poisson)[vars173]}
\NormalTok{), }\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##            OLS Poisson
## pcnv    -0.132  -0.402
## avgsen  -0.011  -0.024
## tottime  0.012   0.024
## ptime86 -0.041  -0.099
## qemp86  -0.051  -0.038
## inc86   -0.001  -0.008
## black    0.327   0.661
## hispan   0.194   0.500
## born60  -0.022  -0.051
\end{verbatim}

\begin{itemize}
\tightlist
\item
  \texttt{pcnv}（有罪判決割合）: \(\Delta pcnv = 0.10\) → 逮捕回数約
  \(4\%\) {[}\(0.402 \times 0.10\){]} 減少
\item
  \texttt{black} 係数 \(0.661\): 黒人男性の期待逮捕回数は他条件一定で
  \(100[\exp(0.661)-1] \approx 93.7\%\) 高い
\end{itemize}

\normalsize
\end{frame}

\hypertarget{ux6253ux3061ux5207ux308aux56deux5e30ux30e2ux30c7ux30ebux3068ux5207ux65adux56deux5e30ux30e2ux30c7ux30eb}{%
\section{17-4
打ち切り回帰モデルと切断回帰モデル}\label{ux6253ux3061ux5207ux308aux56deux5e30ux30e2ux30c7ux30ebux3068ux5207ux65adux56deux5e30ux30e2ux30c7ux30eb}}

\begin{frame}{打ち切りデータと切断データの違い}
\protect\hypertarget{ux6253ux3061ux5207ux308aux30c7ux30fcux30bfux3068ux5207ux65adux30c7ux30fcux30bfux306eux9055ux3044}{}
\textbf{打ち切り回帰 (censored regression)}: -
説明変数は全観測で利用可能 - 被説明変数 \(y_i\) が閾値を超えると観測不可
- 例: トップコーディング、存続期間分析 - Tobit
の数学的構造と同じだが\textbf{解釈が異なる}

\textbf{切断回帰 (truncated regression)}: - \(y\)
が閾値以上（または以下）の観測のみがサンプルに含まれる -
説明変数の情報もない - 例: 一定所得以下の家計のみを対象とした調査
\end{frame}

\begin{frame}{17-4a 打ち切り正規回帰モデル}
\protect\hypertarget{a-ux6253ux3061ux5207ux308aux6b63ux898fux56deux5e30ux30e2ux30c7ux30eb}{}
母集団モデル {[}17.36, 17.37{]}:
\[y_i = \beta_0 + \mathbf{x}_i\boldsymbol{\beta} + u_i, \quad u_i|\mathbf{x}_i, c_i \sim \text{Normal}(0, \sigma^2)\]
\[w_i = \min(y_i, c_i)\]

（\(c_i\): 打ち切り閾値; 右打ち切りの場合）

\begin{itemize}
\tightlist
\item
  打ち切り観測の密度 {[}17.38{]}:
  \(f(w|\mathbf{x}_i, c_i) = 1 - \Phi[(c_i - \mathbf{x}_i\boldsymbol{\beta})/\sigma]\)
  （\(w = c_i\)）
\item
  打ち切りなし観測の密度 {[}17.39{]}:
  \(f(w|\mathbf{x}_i, c_i) = (1/\sigma)\phi[(w - \mathbf{x}_i\boldsymbol{\beta})/\sigma]\)
  （\(w < c_i\)）
\item
  \textbf{注意}: Tobit と違い \(\beta_j\) は線形回帰と同様に解釈可能
\end{itemize}
\end{frame}

\begin{frame}{打ち切りとTobitの比較}
\protect\hypertarget{ux6253ux3061ux5207ux308aux3068tobitux306eux6bd4ux8f03}{}
\begin{longtable}[]{@{}lll@{}}
\toprule
& Tobit (コーナー解) & 打ち切り回帰 \\
\midrule
\endhead
ゼロの意味 & 経済的最適化の結果 & データ収集の問題 \\
\(\beta_j\) の解釈 & \(E(y^*|\mathbf{x})\) への偏効果 &
\(E(y|\mathbf{x})\) への直接的効果 \\
OLS適用 & 不一致（バイアスあり） & 不一致（バイアスあり） \\
代表例 & 年間就業時間 & 上限打ち切りされた賃金 \\
\bottomrule
\end{longtable}
\end{frame}

\begin{frame}[fragile]{例17.4: 再犯の存続期間分析 (RECID)}
\protect\hypertarget{ux4f8b17.4-ux518dux72afux306eux5b58ux7d9aux671fux9593ux5206ux6790-recid}{}
\begin{itemize}
\tightlist
\item
  データ: 北カロライナ州刑務所出所者 1,445 人
\item
  被説明変数: \(\log(durat)\)（再逮捕までの期間の対数）
\item
  893 人が観察期間内に再逮捕されず（右打ち切り: \texttt{cens\ =\ 1}）
\item
  表 17.6 の再現
\end{itemize}

\footnotesize

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(survival)}
\FunctionTok{data}\NormalTok{(recid)}
\CommentTok{\# 打ち切り正規回帰（右打ち切り）}
\CommentTok{\# cens=1: 打ち切り観測 → 事象指標 = 1 {-} cens}
\NormalTok{res\_cens }\OtherTok{\textless{}{-}} \FunctionTok{survreg}\NormalTok{(}
  \FunctionTok{Surv}\NormalTok{(ldurat, }\DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ cens) }\SpecialCharTok{\textasciitilde{}}\NormalTok{ workprg }\SpecialCharTok{+}\NormalTok{ priors }\SpecialCharTok{+}\NormalTok{ tserved }\SpecialCharTok{+}
\NormalTok{    felon }\SpecialCharTok{+}\NormalTok{ alcohol }\SpecialCharTok{+}\NormalTok{ drugs }\SpecialCharTok{+}\NormalTok{ black }\SpecialCharTok{+}\NormalTok{ married }\SpecialCharTok{+}\NormalTok{ educ }\SpecialCharTok{+}\NormalTok{ age,}
  \AttributeTok{data =}\NormalTok{ recid, }\AttributeTok{dist =} \StringTok{"gaussian"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\normalsize
\end{frame}

\begin{frame}[fragile]{例17.4: 推定結果（表17.6）前半}
\protect\hypertarget{ux4f8b17.4-ux63a8ux5b9aux7d50ux679cux886817.6ux524dux534a}{}
\footnotesize

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{coef\_surv }\OtherTok{\textless{}{-}} \FunctionTok{coef}\NormalTok{(res\_cens)}
\NormalTok{se\_surv   }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{(}\FunctionTok{diag}\NormalTok{(}\FunctionTok{vcov}\NormalTok{(res\_cens)))}
\NormalTok{result174 }\OtherTok{\textless{}{-}} \FunctionTok{cbind}\NormalTok{(係数 }\OtherTok{=} \FunctionTok{round}\NormalTok{(coef\_surv, }\DecValTok{3}\NormalTok{),}
                   \AttributeTok{SE   =} \FunctionTok{round}\NormalTok{(se\_surv,   }\DecValTok{3}\NormalTok{))}
\FunctionTok{print}\NormalTok{(result174[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{6}\NormalTok{, ])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##               係数    SE
## (Intercept)  4.099 0.348
## workprg     -0.063 0.120
## priors      -0.137 0.021
## tserved     -0.019 0.003
## felon        0.444 0.145
## alcohol     -0.635 0.144
\end{verbatim}

\normalsize
\end{frame}

\begin{frame}[fragile]{例17.4: 推定結果（表17.6）後半}
\protect\hypertarget{ux4f8b17.4-ux63a8ux5b9aux7d50ux679cux886817.6ux5f8cux534a}{}
\footnotesize

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(result174[}\DecValTok{7}\SpecialCharTok{:}\DecValTok{11}\NormalTok{, ])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           係数    SE
## drugs   -0.298 0.133
## black   -0.543 0.117
## married  0.341 0.140
## educ     0.023 0.025
## age      0.004 0.001
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"σ̂ ="}\NormalTok{, }\FunctionTok{round}\NormalTok{(res\_cens}\SpecialCharTok{$}\NormalTok{scale, }\DecValTok{3}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## σ̂ = 1.81
\end{verbatim}

\normalsize
\end{frame}

\begin{frame}[fragile]{例17.4: 結果の解釈}
\protect\hypertarget{ux4f8b17.4-ux7d50ux679cux306eux89e3ux91c8}{}
\begin{itemize}
\tightlist
\item
  \texttt{priors}（過去の有罪歴）: \(-0.137\) →
  1回増加ごとに再犯までの期間が約 \(14\%\) 短縮
\item
  \texttt{tserved}（服役期間）: \(-0.019\) → 12 ヶ月増加で約 \(22.8\%\)
  短縮（抑止ではなく再犯傾向を反映）
\item
  \texttt{felon}（重罪犯）: \(0.444\) → 非重罪犯より期間が約 \(56\%\)
  {[}\(\exp(0.444)-1\){]} 長い
\item
  \texttt{workprg}（刑務所内作業プログラム）: \(-0.063\)（非有意）
\item
  OLSで打ち切りを無視すると係数が全体的に過小推定
\end{itemize}
\end{frame}

\begin{frame}{17-4b 切断回帰モデル}
\protect\hypertarget{b-ux5207ux65adux56deux5e30ux30e2ux30c7ux30eb}{}
切断正規回帰モデル {[}17.40, 17.41{]}:
\[y = \beta_0 + \mathbf{x\beta} + u, \quad u|\mathbf{x} \sim \text{Normal}(0, \sigma^2)\]

観測は \(y_i \leq c_i\) のときのみ（\(c_i\): 切断閾値）

条件付き密度:
\[g(y|\mathbf{x}_i, c_i) = \frac{f(y|\mathbf{x}_i, \boldsymbol{\beta}, \sigma^2)}{F(c_i|\mathbf{x}_i, \boldsymbol{\beta}, \sigma^2)}, \quad y \leq c_i\]

\begin{itemize}
\tightlist
\item
  切断標本に OLS を適用すると \(\beta_j\) をゼロ方向にバイアス（図 17.4
  参照）
\item
  正規性・均一分散の違反時は不一致
\end{itemize}
\end{frame}

\hypertarget{ux6a19ux672cux9078ux629eux4feeux6b63}{%
\section{17-5 標本選択修正}\label{ux6a19ux672cux9078ux629eux4feeux6b63}}

\begin{frame}{非無作為標本選択の問題}
\protect\hypertarget{ux975eux7121ux4f5cux70baux6a19ux672cux9078ux629eux306eux554fux984c}{}
\begin{itemize}
\tightlist
\item
  \textbf{非無作為標本選択}: 観測されるかどうかが \(y_i\) や \(u_i\)
  に依存
\item
  \textbf{偶発的打ち切り (incidental truncation)}: 別の変数の結果として
  \(y\) が観測されない

  \begin{itemize}
  \tightlist
  \item
    例: 賃金提示 \(y = \log(wage^o)\) は就業者のみ観測
  \item
    就業決定と賃金提示は共通の観測不能要因を持つ可能性
  \item
    これまでの賃金例は全てこの問題を抱えている
  \end{itemize}
\end{itemize}
\end{frame}

\begin{frame}{17-5a 選択標本でOLSが一致する条件}
\protect\hypertarget{a-ux9078ux629eux6a19ux672cux3067olsux304cux4e00ux81f4ux3059ux308bux6761ux4ef6}{}
母集団モデル {[}17.42{]}:
\[y = \beta_0 + \beta_1 x_1 + \cdots + \beta_k x_k + u, \quad E(u|x_1, \ldots, x_k) = 0\]

選択指標 \(s_i\): \(s_i = 1\) のとき観測、\(s_i = 0\) のとき非観測

\textbf{外生的標本選択} → OLS 一致: 1. \(s\) が説明変数 \(\mathbf{x}\)
のみの関数 2. \(s\) が \((\mathbf{x}, u)\) と独立

\textbf{内生的標本選択} → OLS 不一致: - 選択が誤差項 \(u\)
に直接依存（例: 切断標本、偶発的打ち切り）
\end{frame}

\begin{frame}{17-5b 偶発的打ち切り: モデル設定}
\protect\hypertarget{b-ux5076ux767aux7684ux6253ux3061ux5207ux308a-ux30e2ux30c7ux30ebux8a2dux5b9a}{}
人口モデル {[}17.46, 17.47{]}:
\[y = \mathbf{x\beta} + u, \quad E(u|\mathbf{x}) = 0\]
\[s = \mathbf{1}[\mathbf{z\gamma} + v \geq 0]\]

仮定: - \(\mathbf{x}\) は \(\mathbf{z}\) の真部分集合
(\(\mathbf{x} \subsetneq \mathbf{z}\)): \textbf{除外制約}が重要 - \(v\)
は標準正規分布に従う - \((u, v)\) は \(\mathbf{z}\)
から独立、\(\text{Corr}(u, v) = \rho\)
\end{frame}

\begin{frame}{偶発的打ち切りとOLSバイアス}
\protect\hypertarget{ux5076ux767aux7684ux6253ux3061ux5207ux308aux3068olsux30d0ux30a4ux30a2ux30b9}{}
\(\rho \neq 0\) のとき、選択標本 (\(s = 1\)) での条件付き期待値
{[}17.48{]}:
\[E(y|\mathbf{z}, s=1) = \mathbf{x\beta} + \rho\lambda(\mathbf{z\gamma})\]

\textbf{逆ミルズ比}:
\(\lambda(\mathbf{z\gamma}) = \phi(\mathbf{z\gamma})/\Phi(\mathbf{z\gamma})\)

\begin{itemize}
\tightlist
\item
  \(\rho = 0\) なら \(\lambda(\mathbf{z\gamma})\) は不要 → OLS で
  \(\boldsymbol{\beta}\) を一致推定
\item
  \(\rho \neq 0\) なら \(\lambda(\mathbf{z\gamma})\)
  を省略することがバイアスの原因
\end{itemize}
\end{frame}

\begin{frame}{Heckit法の手順}
\protect\hypertarget{heckitux6cd5ux306eux624bux9806}{}
選択方程式のプロビットモデル {[}17.49{]}:
\[P(s=1|\mathbf{z}) = \Phi(\mathbf{z\gamma})\]

\textbf{2段階推定（Heckman, 1976）}:

\begin{enumerate}
[(i)]
\item
  全 \(n\) 観測でプロビット \(s_i\) on \(\mathbf{z}_i\) を推定
  \(\quad\Rightarrow\hat{\boldsymbol{\gamma}} \Rightarrow \hat{\lambda}_i = \lambda(\mathbf{z}_i\hat{\boldsymbol{\gamma}})\)
\item
  選択サンプル（\(s_i = 1\)）で回帰 {[}17.50{]}:
  \[y_i \text{ on } \mathbf{x}_i,\, \hat{\lambda}_i\]
\end{enumerate}

\begin{itemize}
\tightlist
\item
  \(\hat{\lambda}_i\) の \(t\) 統計量:
  \(H_0: \rho = 0\)（選択バイアスなし）の検定
\item
  除外制約（\(\mathbf{x} \subsetneq \mathbf{z}\)）がなければ識別が困難
\end{itemize}
\end{frame}

\begin{frame}[fragile]{例17.5: 既婚女性の賃金提示方程式 (MROZ)}
\protect\hypertarget{ux4f8b17.5-ux65e2ux5a5aux5973ux6027ux306eux8cc3ux91d1ux63d0ux793aux65b9ux7a0bux5f0f-mroz}{}
\begin{itemize}
\tightlist
\item
  賃金方程式: \(\log(wage)\) on \texttt{educ}, \texttt{exper},
  \texttt{expersq}（428 人）
\item
  選択方程式: \texttt{inlf} on 賃金変数 + \texttt{nwifeinc},
  \texttt{age}, \texttt{kidslt6}, \texttt{kidsge6}（753 人）
\item
  \textbf{除外変数}: \texttt{nwifeinc}, \texttt{age}, \texttt{kidslt6},
  \texttt{kidsge6}
  （賃金提示には影響しないが就業参加には影響すると仮定）
\item
  表 17.7 の再現
\end{itemize}
\end{frame}

\begin{frame}[fragile]{例17.5: Heckit推定（手動実装）}
\protect\hypertarget{ux4f8b17.5-heckitux63a8ux5b9aux624bux52d5ux5b9fux88c5}{}
\footnotesize

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(mroz)}
\CommentTok{\# Step 1: 選択方程式のプロビット（全753人）}
\NormalTok{sel\_probit }\OtherTok{\textless{}{-}} \FunctionTok{glm}\NormalTok{(inlf }\SpecialCharTok{\textasciitilde{}}\NormalTok{ nwifeinc }\SpecialCharTok{+}\NormalTok{ educ }\SpecialCharTok{+}\NormalTok{ exper }\SpecialCharTok{+}\NormalTok{ expersq }\SpecialCharTok{+}
\NormalTok{                    age }\SpecialCharTok{+}\NormalTok{ kidslt6 }\SpecialCharTok{+}\NormalTok{ kidsge6,}
                  \AttributeTok{data =}\NormalTok{ mroz, }\AttributeTok{family =} \FunctionTok{binomial}\NormalTok{(}\AttributeTok{link =} \StringTok{"probit"}\NormalTok{))}
\CommentTok{\# 逆ミルズ比の計算}
\NormalTok{zg\_hat }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(sel\_probit, }\AttributeTok{type =} \StringTok{"link"}\NormalTok{)}
\NormalTok{imr    }\OtherTok{\textless{}{-}} \FunctionTok{dnorm}\NormalTok{(zg\_hat) }\SpecialCharTok{/} \FunctionTok{pnorm}\NormalTok{(zg\_hat)}
\CommentTok{\# Step 2: 選択サンプル（就業者428人）でのOLS}
\NormalTok{mroz\_work }\OtherTok{\textless{}{-}} \FunctionTok{subset}\NormalTok{(mroz, inlf }\SpecialCharTok{==} \DecValTok{1}\NormalTok{)}
\NormalTok{imr\_work  }\OtherTok{\textless{}{-}}\NormalTok{ imr[mroz}\SpecialCharTok{$}\NormalTok{inlf }\SpecialCharTok{==} \DecValTok{1}\NormalTok{]}
\NormalTok{res\_heckit }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(lwage }\SpecialCharTok{\textasciitilde{}}\NormalTok{ educ }\SpecialCharTok{+}\NormalTok{ exper }\SpecialCharTok{+}\NormalTok{ expersq }\SpecialCharTok{+}\NormalTok{ imr\_work,}
                 \AttributeTok{data =}\NormalTok{ mroz\_work)}
\end{Highlighting}
\end{Shaded}

\normalsize
\end{frame}

\begin{frame}[fragile]{例17.5: OLS vs Heckit（表17.7）}
\protect\hypertarget{ux4f8b17.5-ols-vs-heckitux886817.7}{}
\footnotesize

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# OLS（選択サンプルのみ）}
\NormalTok{res\_ols175 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(lwage }\SpecialCharTok{\textasciitilde{}}\NormalTok{ educ }\SpecialCharTok{+}\NormalTok{ exper }\SpecialCharTok{+}\NormalTok{ expersq, }\AttributeTok{data =}\NormalTok{ mroz\_work)}
\CommentTok{\# 係数比較}
\NormalTok{ols\_vec }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\FunctionTok{coef}\NormalTok{(res\_ols175), }\AttributeTok{lambda =} \ConstantTok{NA}\NormalTok{)}
\NormalTok{hec\_vec }\OtherTok{\textless{}{-}} \FunctionTok{coef}\NormalTok{(res\_heckit)}
\FunctionTok{names}\NormalTok{(hec\_vec)[}\DecValTok{5}\NormalTok{] }\OtherTok{\textless{}{-}} \StringTok{"lambda"}
\FunctionTok{round}\NormalTok{(}\FunctionTok{cbind}\NormalTok{(}\AttributeTok{OLS =}\NormalTok{ ols\_vec, }\AttributeTok{Heckit =}\NormalTok{ hec\_vec), }\DecValTok{4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                 OLS  Heckit
## (Intercept) -0.5220 -0.5781
## educ         0.1075  0.1091
## exper        0.0416  0.0439
## expersq     -0.0008 -0.0009
## lambda           NA  0.0323
\end{verbatim}

\normalsize
\end{frame}

\begin{frame}[fragile]{例17.5: 選択バイアスの検定}
\protect\hypertarget{ux4f8b17.5-ux9078ux629eux30d0ux30a4ux30a2ux30b9ux306eux691cux5b9a}{}
\footnotesize

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# λ̂ の係数（H₀: ρ = 0 の検定）}
\FunctionTok{round}\NormalTok{(}\FunctionTok{summary}\NormalTok{(res\_heckit)}\SpecialCharTok{$}\NormalTok{coefficients[}\StringTok{"imr\_work"}\NormalTok{, ], }\DecValTok{4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Estimate Std. Error    t value   Pr(>|t|) 
##     0.0323     0.1344     0.2401     0.8104
\end{verbatim}

\normalsize

\begin{itemize}
\tightlist
\item
  \(\hat{\lambda}\) の係数 \(\approx 0.032\)（se
  \(\approx 0.134\)）、\(t \approx 0.239\)
\item
  \(H_0: \rho = 0\) を棄却できない（選択バイアスの証拠なし）
\item
  \texttt{educ} 係数の差は約 0.1 \%ポイント未満（実質的にも差なし）
\item
  \textbf{結論}: この賃金方程式では標本選択修正は不要
\end{itemize}
\end{frame}

\hypertarget{ux307eux3068ux3081}{%
\section{まとめ}\label{ux307eux3068ux3081}}

\begin{frame}[fragile]{第17章のまとめ}
\protect\hypertarget{ux7b2c17ux7ae0ux306eux307eux3068ux3081}{}
\scriptsize

\begin{longtable}[]{@{}llll@{}}
\toprule
モデル & 状況 & 推定法 & R関数 \\
\midrule
\endhead
ロジット & 二値応答 & MLE &
\texttt{glm(...,\ family=binomial("logit"))} \\
プロビット & 二値応答 & MLE &
\texttt{glm(...,\ family=binomial("probit"))} \\
Tobit & コーナー解 & MLE & \texttt{AER::tobit(...,\ left=0)} \\
ポアソン & カウント変数 & QMLE & \texttt{glm(...,\ family=poisson)} \\
打ち切り回帰 & 打ち切りデータ & MLE & \texttt{survival::survreg()} \\
Heckit & 標本選択修正 & 2段階 & 手動: プロビット + OLS \\
\bottomrule
\end{longtable}

\normalsize
\end{frame}

\begin{frame}{まとめ（続き）}
\protect\hypertarget{ux307eux3068ux3081ux7d9aux304d}{}
\begin{itemize}
\tightlist
\item
  \textbf{ロジット・プロビット}: LPMの欠点を克服; APEでOLS係数と比較可能
\item
  \textbf{Tobit}: コーナー解応答（ゼロが最適行動の結果）に使用

  \begin{itemize}
  \tightlist
  \item
    OLS係数より大きい →
    \(\Phi(\bar{\mathbf{x}}\hat{\boldsymbol{\beta}}/\hat{\sigma})\)
    で調整してOLSと比較
  \end{itemize}
\item
  \textbf{ポアソン}: カウント変数; \(\text{Var}=E\) でなくても QMLE
  として一致

  \begin{itemize}
  \tightlist
  \item
    過分散 (\(\hat{\sigma}^2 > 1\)) 時は QMLE 修正標準誤差を使用
  \end{itemize}
\item
  \textbf{打ち切り回帰}: データ収集上の打ち切り; \(\beta_j\)
  は線形解釈可能
\item
  \textbf{Heckit}: 偶発的打ち切りによる選択バイアス修正

  \begin{itemize}
  \tightlist
  \item
    除外制約（\(\mathbf{x} \subsetneq \mathbf{z}\)）が識別に重要
  \item
    \(\hat{\lambda}\) の \(t\) 統計量で選択バイアスを検定
  \end{itemize}
\end{itemize}
\end{frame}

\end{document}
